import { Slide, buildSlide, h2, p, ul, ol, tip, warn, action, table } from './helpers';

export const formCreateSlides: Slide[] = [
  buildSlide(1, 'Welcome to Form Creation', h2('Form Creation Training'), p('Learn to design CRF forms using the AccuraTrial form builder.'), ul(['Use the 5-tab form builder','Add and configure 78+ field types','Set up multi-column layouts','Preview and publish forms']), tip('Based on SOP-016 v7.0')),
  buildSlide(2, 'The Forms Page', h2('Navigating to Forms'), p('Click <strong>Forms</strong> in the sidebar to see all CRF templates.'), p('Page features:'), ul(['Form cards with version, status, and field count','Create New Form button','Template Gallery for pre-built forms','Archive section for retired forms'])),
  buildSlide(3, 'The 5-Tab Form Builder', h2('Builder Structure'), p('Click "Create New Form" to open the builder:'), ol(['<strong>Info</strong> — form name, category, description, version','<strong>Design</strong> — add fields, sections, configure properties','<strong>Layout</strong> — multi-column arrangement','<strong>Edit Checks</strong> — validation rule summary','<strong>Preview</strong> — see form as users will']), action('Open the form builder and explore each tab.')),
  buildSlide(4, 'Adding Fields — Quick Add', h2('Fastest Way to Add Fields'), p('The Design tab toolbar has Quick Add buttons for common fields:'), ul(['Text Input, Number, Date, Time','Dropdown, Radio, Checkbox','Textarea, File Upload','Vital Signs (BP, HR, Temp, Weight)','Section Header, Separator']), p('Click any Quick Add button → field appears immediately in the form.')),
  buildSlide(5, 'Field Types Reference', h2('78 Available Field Types'), table(['Category','Examples'],[['Basic Input','Text, Number, Email, Phone, URL'],['Selection','Dropdown, Radio, Checkbox, Multi-select'],['Clinical Vitals','Blood Pressure, Heart Rate, Temperature, SpO2'],['Medical Data','ICD-10, Lab Results, Medication, Dosage'],['Advanced','Calculated, Data Table, Question Table, Criteria List'],['Layout','Section, Separator, Inline Group, Repeating Group'],['PHI Types','Patient Name, DOB, SSN, Address, MRN']]), tip('Use PHI field types for automatic data protection marking.')),
  buildSlide(6, 'Configuring Field Properties', h2('Field Settings'), p('Click any field to open its properties panel:'), ul(['<strong>Label</strong> — display name','<strong>Variable Name</strong> — database column identifier','<strong>Required</strong> — must be filled before submission','<strong>PHI</strong> — marks as protected health information','<strong>Help Text</strong> — guidance shown below field','<strong>Default Value</strong> — pre-populated value','<strong>Validation</strong> — add rules (links to Validation Rules module)']), warn('Variable names cannot be changed after form is published.')),
  buildSlide(7, 'Sections and Layout', h2('Organizing Your Form'), p('<strong>Sections:</strong> Group related fields under headers. Drag to reorder.'), p('<strong>Layout Tab:</strong> Configure multi-column display:'), ul(['1-column (default) — full width','2-column — side by side fields','3-column — compact display','Mixed — different widths per field (25%, 50%, 75%, 100%)']), action('Try arranging fields in a 2-column layout.')),
  buildSlide(8, 'Preview and Publish', h2('Finalizing Your Form'), p('<strong>Preview Tab:</strong> See exactly how users will experience the form. Test on desktop, tablet, and mobile views.'), p('<strong>Publishing:</strong>'), ol(['Click "Save" — requires e-signature','Review the form summary','Click "Publish" to make available for data entry','Published forms appear in Event-CRF Assignment']), warn('Published forms are versioned. Edits create a new version — original is preserved.')),
  buildSlide(9, 'Pre-Built Templates', h2('Template Gallery'), p('Save time with pre-built templates:'), ul(['Complete Vital Signs — BP, HR, RR, Temp, SpO2, Weight, Height','Standard Demographics — name, DOB, gender, ethnicity, race','Adverse Event — AE term, severity, causality, outcome, dates','Concomitant Medication — drug, dose, route, indication, dates','Chemistry Panel — 15 standard lab values with ranges','Inclusion/Exclusion — criteria checklist with pass/fail']), p('Import any template and customize for your protocol.')),
  buildSlide(10, 'Module Summary', h2('Key Takeaways'), ul(['5-tab builder: Info → Design → Layout → Edit Checks → Preview','78+ field types across 7 categories','Quick Add for fastest field creation','E-signature required to save forms (21 CFR Part 11)','Forms are versioned — never deleted, only archived','Pre-built templates available for common form types','Variable names are permanent after publishing']), p('<strong>Ready for the quiz!</strong>'))
];

export const patientMgmtSlides: Slide[] = [
  buildSlide(1, 'Welcome to Patient Management', h2('Patient/Subject Management Training'), p('Learn to enroll patients, manage visits, and track progress.'), ul(['Enroll new subjects','Generate unique subject IDs','Navigate patient records','Track visit completion']), tip('Based on SOP-026 v6.0')),
  buildSlide(2, 'The Patients Page', h2('Patient List View'), p('Click <strong>Patients</strong> in the sidebar.'), p('Features:'), ul(['Patient table with ID, status, site, enrollment date','Search and filter by site, status, visit','Enroll New Patient button','Click any row to view patient details'])),
  buildSlide(3, 'Enrolling a New Patient', h2('3-Step Enrollment Wizard'), ol(['<strong>Step 1: Subject ID</strong> — auto-generated or manual entry based on study config','<strong>Step 2: Demographics</strong> — required screening data (DOB, gender, initials)','<strong>Step 3: Assignment</strong> — assign to site, study group, and first visit']), p('After enrollment, the patient appears in the list with scheduled visits.'), action('Try enrolling a test patient using the wizard.')),
  buildSlide(4, 'Patient Detail View', h2('The Patient Record'), p('Click a patient row to see their full record:'), ul(['<strong>Header</strong> — Subject ID, status, enrollment date, site','<strong>Visit Timeline</strong> — columns for each scheduled visit','<strong>Form Chips</strong> — colored indicators for each form per visit','<strong>Progress Bar</strong> — overall completion percentage']), p('Form chip colors: gray (not started), blue (in progress), green (complete), purple (signed).')),
  buildSlide(5, 'Managing Visits', h2('Working with Patient Visits'), p('Each patient has scheduled visits defined by the study protocol:'), ul(['Visits appear as columns in the patient view','Click a form chip to open it for data entry','Unscheduled visits can be added (adverse events, early termination)','Visit windows show acceptable timing ranges']), tip('Forms within a visit may have dependencies — complete them in order.')),
  buildSlide(6, 'Patient Search and Filters', h2('Finding Patients Quickly'), p('Use the search panel for advanced filtering:'), ul(['Search by Subject ID, name initials, or MRN','Filter by site, enrollment status, visit status','Filter by form completion status','Sort by enrollment date, last activity, or ID']), action('Try searching for a patient by their Subject ID.')),
  buildSlide(7, 'Module Summary', h2('Key Takeaways'), ul(['Enroll patients via 3-step wizard','Subject IDs are auto-generated or manual per study config','Patient detail shows visit timeline with form chips','Form chip colors indicate completion status','Use search and filters to find patients quickly','Unscheduled visits available for protocol deviations']), p('<strong>Ready for the quiz!</strong>'))
];

export const valRulesSlides: Slide[] = [
  buildSlide(1, 'Welcome to Validation Rules', h2('Validation Rules Training'), p('Learn to create edit checks and branching logic for data quality.'), ul(['Three methods to create rules','Configure severity levels','Set up branching/skip logic','Test and manage rules']), tip('Based on SOP-019 v8.0')),
  buildSlide(2, 'Why Validation Rules Matter', h2('Data Quality Enforcement'), p('Validation rules automatically check data as it is entered:'), ul(['Catch errors before they reach the database','Ensure values are within acceptable ranges','Enforce required field combinations','Flag unusual values for manual review','Reduce query volume by preventing bad data']), warn('Per 21 CFR Part 11 §11.10(h), systems must have appropriate controls for data accuracy.')),
  buildSlide(3, 'Getting to Validation Rules', h2('Navigation'), p('Click <strong>Validation Rules</strong> in the sidebar.'), ol(['Select a form from the dropdown','See all fields displayed as cards','Each card shows existing rules with indicators','Use the toolbar to add new rules']), p('Cards show: field name, type, current rule count, and quick-add button.')),
  buildSlide(4, 'Method 1: Quick Add', h2('Fastest Way to Add Rules'), p('Quick Add offers 28 pre-built rule templates in 5 categories:'), table(['Category','Examples'],[['Required','Required field, Required if other field has value'],['Range','Min/Max value, Between range, Greater than field'],['Format','Email format, Phone format, Date format, Custom regex'],['Comparison','Equal to field, Not equal, Less than another field'],['Clinical','Vital sign ranges, Lab value limits, BMI calculation']]), action('Try adding a "Required" rule using Quick Add.')),
  buildSlide(5, 'Method 2: AI Rule Suggester', h2('Intelligent Recommendations'), p('The AI Rule Suggester analyzes field context and suggests appropriate rules:'), ol(['Click the AI wand icon on any field card','AI analyzes field name, type, and context','Suggestions appear with confidence scores','Accept suggestions with one click']), p('Example: For a "Heart Rate" field, AI suggests range 40-200 bpm with "Create Query" severity.')),
  buildSlide(6, 'Method 3: Custom Rule Builder', h2('The Rule Builder Wizard'), p('For complex rules, use the 6-step wizard:'), ol(['<strong>Which field?</strong> — select target field','<strong>What check?</strong> — choose from 30+ check types in mega-dropdown','<strong>Configure</strong> — set values, ranges, or patterns','<strong>Severity</strong> — Block Save (hard error) or Create Query (soft warning)','<strong>Name/Message</strong> — custom rule name and error message','<strong>Create</strong> — click to save the rule']), action('Create a custom range check using the wizard.')),
  buildSlide(7, 'Severity Levels', h2('Block Save vs Create Query'), table(['Severity','Effect','Use When'],[['Block Save (Red)','Prevents form submission','Data is definitely wrong (negative age, future dates)'],['Create Query (Yellow)','Allows save, auto-creates query','Data is unusual but possible (HR of 180)']]), p('Queries created by validation rules are auto-assigned based on workflow routing configuration.')),
  buildSlide(8, 'Branching Logic', h2('Conditional Field Display'), p('Branching logic shows/hides fields based on other field values:'), ol(['Click "Branching Logic" tab','Select the field to conditionally show','Choose the controlling field','Set the condition (equals, not equals, contains)','Configure the trigger value']), p('<strong>Example:</strong> Show "Pregnancy Details" section only when Gender = Female AND Age 12-55.'), p('The interactive SVG diagram visualizes all branching relationships.')),
  buildSlide(9, 'Testing and Managing Rules', h2('Verification'), p('<strong>Testing:</strong> Use inline test to verify rules fire correctly with boundary values.'), p('<strong>Managing:</strong>'), ul(['Enable/disable rules without deleting','Edit existing rules to adjust thresholds','Delete rules that are no longer needed','Refresh to see rules from other users']), warn('Rule changes require e-signature per 21 CFR Part 11.')),
  buildSlide(10, 'Module Summary', h2('Key Takeaways'), ul(['Three methods: Quick Add (28 templates), AI Suggester, Custom Builder','Two severities: Block Save (hard) vs Create Query (soft)','30+ check types in the mega-dropdown','Branching logic shows/hides fields conditionally','AI analyzes field context for intelligent suggestions','All rule changes require e-signature','Test rules with boundary values before activating']), p('<strong>Ready for the quiz!</strong>'))
];
