import { Slide, buildSlide, h2, p, ul, ol, tip, warn, action, table } from './helpers';

export const dataExportSlides: Slide[] = [
  buildSlide(1, 'Welcome to Data Export', h2('Data Export Training'), p('Learn to export clinical data in multiple formats for analysis and submission.'), ul(['Export formats: PDF, Excel, CSV, ODM XML','Configure export options','Generate regulatory packages','Schedule recurring exports']), tip('Based on SOP-022 v5.0')),
  buildSlide(2, 'The Export Modal', h2('Starting an Export'), p('Access exports from the Reports page or patient list:'), ol(['Click "Export Data" button','Select export scope (study, site, patient, form)','Choose format: PDF, Excel, CSV, ODM XML, Tab-Delimited','Configure options (date range, include audit trail, etc.)','Click "Generate Export"']), action('Try exporting a small dataset as CSV.')),
  buildSlide(3, 'Export Formats', h2('Choosing the Right Format'), table(['Format','Best For'],[['PDF','Regulatory submission, printing, archival'],['Excel','Data review, ad-hoc analysis'],['CSV','Statistical analysis (SAS, R, Python)'],['ODM XML','Regulatory submission (FDA standard)'],['Tab-Delimited','Legacy system import']]), tip('ODM XML is the FDA-preferred format for electronic submissions.')),
  buildSlide(4, 'Export Options', h2('Configuration'), ul(['<strong>Date Range</strong> — export data from specific period','<strong>Include Audit Trail</strong> — append change history','<strong>Include Queries</strong> — export query threads','<strong>Include Signatures</strong> — show e-signature metadata','<strong>Anonymize</strong> — strip PHI identifiers','<strong>Locked Data Only</strong> — export only locked/final records']), warn('Anonymized exports remove all 18 HIPAA identifiers. Verify with your IRB.')),
  buildSlide(5, 'Module Summary', h2('Key Takeaways'), ul(['Five export formats available','ODM XML for FDA submissions','CSV/Excel for statistical analysis','Options to include/exclude audit trails, queries, signatures','Anonymization available for de-identified datasets','Only authorized roles can export data']), p('<strong>Ready for the quiz!</strong>'))
];

export const reportsSlides: Slide[] = [
  buildSlide(1, 'Welcome to Reports', h2('Reports and Analytics Training'), p('Learn to use the reporting dashboard for study oversight.'), ul(['Enrollment reports','Data quality metrics','Query analytics','Custom dashboards']), tip('Based on SOP-031 v5.0')),
  buildSlide(2, 'The Reports Dashboard', h2('Available Report Types'), p('Navigate to <strong>Reports</strong> in the sidebar.'), ul(['<strong>Enrollment Dashboard</strong> — screening, enrollment, completion rates by site','<strong>Data Quality</strong> — missing data, query rates, validation failure patterns','<strong>Query Analytics</strong> — open/closed trends, response times, by category','<strong>Site Performance</strong> — per-site metrics and comparisons','<strong>Compliance</strong> — SDV progress, signature status, training completion']), action('Open the Reports page and explore each report type.')),
  buildSlide(3, 'Enrollment Reports', h2('Tracking Patient Progress'), p('The enrollment dashboard shows:'), ul(['Screening vs enrollment funnel','Enrollment by site (bar chart)','Enrollment over time (trend line)','Projected vs actual enrollment','Screen failure reasons']), p('Use date range filters to focus on specific periods.')),
  buildSlide(4, 'Data Quality Reports', h2('Monitoring Data Integrity'), p('Data quality metrics include:'), ul(['Form completion rates by visit','Missing data percentage per field','Query generation rate (queries per 100 forms)','Validation failure patterns','Overdue query count and aging']), tip('Review data quality weekly to catch systematic issues early.')),
  buildSlide(5, 'Module Summary', h2('Key Takeaways'), ul(['Five main report categories available','Enrollment reports track patient progress and projections','Data quality reports identify systematic issues','Query analytics show response times and trends','Reports are filterable by date, site, and study','All roles can view reports (content varies by role)']), p('<strong>Ready for the quiz!</strong>'))
];

export const randomizeSlides: Slide[] = [
  buildSlide(1, 'Welcome to Randomization', h2('Randomization Training'), p('Learn to configure and execute patient randomization.'), ul(['Set up randomization algorithms','Manage sealed randomization lists','Perform patient randomization','Handle stratification','Emergency unblinding']), tip('Based on SOP-030 v5.0')),
  buildSlide(2, 'Randomization Configuration', h2('Setting Up'), p('Navigate to <strong>Randomization</strong> (via study settings).'), p('Configuration options:'), ul(['<strong>Algorithm</strong> — simple, block, stratified, minimization','<strong>Ratio</strong> — e.g., 1:1, 2:1 treatment vs control','<strong>Stratification</strong> — by site, gender, age group, severity','<strong>Block Size</strong> — fixed or variable block sizes','<strong>Seed</strong> — random seed for reproducibility']), warn('Randomization configuration must be locked before first patient is randomized.')),
  buildSlide(3, 'Sealed Lists', h2('Pre-Generated Assignments'), p('Randomization uses sealed, pre-generated lists:'), ul(['Lists are generated by the algorithm and sealed','Each entry is revealed only at randomization time','Audit trail records who unsealed each entry and when','Lists can be uploaded from external RTSM systems','Remaining allocations are never visible to blinded staff']), p('The sealed list approach ensures allocation concealment per ICH E9.')),
  buildSlide(4, 'Performing Randomization', h2('Randomizing a Patient'), ol(['Navigate to the patient record','Click "Randomize" button','Confirm patient meets eligibility criteria','System assigns treatment arm from sealed list','Assignment is revealed and recorded','Certificate of randomization generated']), warn('Randomization cannot be undone. Verify eligibility carefully before clicking.')),
  buildSlide(5, 'Emergency Unblinding', h2('Breaking the Blind'), p('In medical emergencies, the blind may need to be broken:'), ol(['Click "Emergency Unblind" for the patient','Enter reason for unblinding','Provide e-signature (two authorized users required)','Treatment assignment is revealed','Event is logged in audit trail and reported to sponsor']), warn('Emergency unblinding is a serious protocol deviation. Only use when medically necessary.')),
  buildSlide(6, 'Module Summary', h2('Key Takeaways'), ul(['Four randomization algorithms supported','Sealed lists ensure allocation concealment','Stratification balances treatment groups','Randomization requires eligibility confirmation','Cannot be undone once executed','Emergency unblinding requires dual authorization','Full audit trail for all randomization actions']), p('<strong>Ready for the quiz!</strong>'))
];
