import { Slide, buildSlide, h2, p, ul, ol, tip, warn, action, table } from './helpers';

export const dataLocksSlides: Slide[] = [
  buildSlide(1, 'Welcome to Data Lock Management', h2('Data Lock Training'), p('Learn to freeze, lock, and manage clinical data states.'), ul(['Understand freeze vs lock','Perform casebook readiness checks','Process unlock requests','Execute study-level locks']), tip('Based on SOP-018 v6.0')),
  buildSlide(2, 'Data States Overview', h2('Freeze vs Lock'), table(['State','Effect','Reversible?'],[['Open','Data can be edited freely','N/A'],['Frozen','No edits allowed','Yes — Data Manager can unfreeze'],['Locked','Permanently sealed','No — requires formal unlock request']]), p('Data flows: Open → Frozen → Locked (for database lock)')),
  buildSlide(3, 'The Data Lock Dashboard', h2('5-Tab Interface'), p('Navigate to Data Locks in the sidebar. Five tabs:'), ol(['<strong>Casebook Readiness</strong> — check if patients are ready for lock','<strong>Locked Records</strong> — view all locked CRFs','<strong>Unlock Requests</strong> — manage unlock request workflow','<strong>Data Sanitation</strong> — final quality checks','<strong>Study Lock</strong> — execute full database lock'])),
  buildSlide(4, 'Casebook Readiness', h2('Pre-Lock Verification'), p('Before locking, verify each patient casebook is complete:'), ul(['All required forms submitted and signed','All queries resolved (no open queries)','SDV complete for required fields','No pending workflow tasks','E-signatures valid and current']), action('Run a casebook readiness check on a test patient.')),
  buildSlide(5, 'Freezing and Locking Records', h2('Applying Data States'), p('<strong>Freezing a form:</strong>'), ol(['Open the Data Lock dashboard','Select patient(s) and form(s)','Click "Freeze Selected"','Confirm with e-signature']), p('<strong>Locking:</strong> Same process but click "Lock Selected". Locked data cannot be modified without formal unlock request.'), warn('Locking is intended to be permanent. Only lock when data is submission-ready.')),
  buildSlide(6, 'Unlock Requests', h2('When Locked Data Needs Changes'), p('If locked data needs correction:'), ol(['Requestor submits unlock request with reason','Data Manager reviews the request','If approved: record is temporarily unfrozen','Correction is made with reason-for-change','Record is re-locked after correction']), p('Full audit trail is maintained throughout.')),
  buildSlide(7, 'Study-Level Lock', h2('Database Lock'), p('The final step before regulatory submission:'), ul(['All patients must pass casebook readiness','All queries must be closed','All SDV must be complete','Study Lock freezes entire database','Requires senior e-signature authorization']), warn('Study lock is irreversible without formal protocol amendment.')),
  buildSlide(8, 'Module Summary', h2('Key Takeaways'), ul(['Frozen = temporary hold; Locked = permanent seal','Casebook readiness checks ensure completeness before lock','Unlock requests follow formal workflow with audit trail','Study-level lock seals the entire database for submission','All lock/unlock actions require e-signature','Only Data Managers and Administrators can manage locks']), p('<strong>Ready for the quiz!</strong>'))
];

export const eSignSlides: Slide[] = [
  buildSlide(1, 'Welcome to E-Signatures', h2('Electronic Signature Training'), p('Learn how electronic signatures work in AccuraTrial per 21 CFR Part 11.'), ul(['Understand the legal equivalence of e-signatures','Apply signatures correctly','Know when signatures are required','Manage signature manifestations'])),
  buildSlide(2, 'What Is an Electronic Signature?', h2('Legal Equivalence'), p('Under 21 CFR Part 11 §11.50, electronic signatures are legally equivalent to handwritten signatures.'), p('<strong>Two-component authentication:</strong>'), ol(['<strong>Username</strong> — identifies who is signing','<strong>Password</strong> — verifies it is really them']), p('Plus a <strong>reason/meaning</strong>: review, approval, responsibility, or authorship.')),
  buildSlide(3, 'When Signatures Are Required', h2('Signature Triggers'), table(['Action','Signature Required?'],[['Submit a completed form','Yes'],['Save a form as draft','No'],['Create or modify validation rules','Yes'],['Lock or freeze data','Yes'],['Close a query','Yes'],['Publish a form template','Yes'],['Approve an unlock request','Yes']]), tip('The system prompts you automatically when a signature is needed.')),
  buildSlide(4, 'Applying an E-Signature', h2('The Signing Process'), ol(['Complete the required action (e.g., submit form)','Signature modal appears','Enter your <strong>username</strong>','Enter your <strong>password</strong>','Select or type the <strong>reason</strong> for signing','Click "Sign"']), p('The system records: who signed, when (UTC timestamp), what was signed, and why.'), action('Practice applying an e-signature on a test form.')),
  buildSlide(5, 'Signature Manifestation', h2('What Gets Recorded'), p('Every signature stores:'), ul(['Full name of signer','Date and time (UTC)','Meaning of signature (e.g., "I reviewed and approve this data")','The exact data state at time of signing']), warn('If data changes after signing, the signature is automatically invalidated. A new signature is required.')),
  buildSlide(6, 'Module Summary', h2('Key Takeaways'), ul(['E-signatures are legally binding under 21 CFR Part 11','Two components: username + password + reason','Required for: form submission, rule changes, data locks, query closure','Signatures are invalidated if signed data is modified','System automatically prompts when signature is needed','All signatures are recorded in the audit trail']), p('<strong>Ready for the quiz!</strong>'))
];

export const sdvSlides: Slide[] = [
  buildSlide(1, 'Welcome to SDV', h2('Source Data Verification Training'), p('Learn to perform SDV — verifying that EDC data matches source documents.'), ul(['Navigate the SDV dashboard','Mark fields as verified','Track verification progress','Complete SDV requirements']), tip('Based on SOP-028 v5.0')),
  buildSlide(2, 'What Is SDV?', h2('Source Data Verification'), p('SDV ensures data entered into the EDC matches the original source documents (medical charts, lab reports, etc.).'), p('<strong>ICH E6(R2) §6.4.9:</strong> Monitors should verify that data reported in the CRF are consistent with the source documents.'), p('Not all fields require SDV — the study protocol and monitoring plan define which fields are SDV-required.')),
  buildSlide(3, 'The SDV Dashboard', h2('Monitoring Hub'), p('Click <strong>SDV</strong> in the sidebar (Monitor role).'), p('Dashboard shows:'), ul(['Overall SDV progress percentage','Per-patient verification status','Per-form verification breakdown','Fields requiring verification highlighted','History of completed verifications'])),
  buildSlide(4, 'Performing SDV', h2('Verification Process'), ol(['Open a patient form marked for SDV','SDV-required fields have a verification icon','Compare field value to source document','If correct: click the checkmark to verify','If discrepancy: create a query on the field']), p('Verified fields show a green shield icon. Unverified fields remain marked.'), action('Try verifying a field against its source document.')),
  buildSlide(5, 'SDV Progress Tracking', h2('Monitoring Completion'), p('Track SDV progress at multiple levels:'), ul(['<strong>Study level</strong> — overall percentage complete','<strong>Site level</strong> — per-site progress for targeted monitoring','<strong>Patient level</strong> — individual casebook verification status','<strong>Form level</strong> — which forms are fully verified']), p('SDV must be 100% complete before data lock for studies requiring it.')),
  buildSlide(6, 'Module Summary', h2('Key Takeaways'), ul(['SDV verifies EDC data matches source documents','Only Monitor role performs SDV','SDV-required fields are defined by study protocol','Verify correct → checkmark; discrepancy → create query','SDV must be complete before database lock','Track progress at study, site, patient, and form levels']), p('<strong>Ready for the quiz!</strong>'))
];

export const workflowSlides: Slide[] = [
  buildSlide(1, 'Welcome to Workflow Management', h2('Workflow Training'), p('Learn to configure per-form workflows and manage tasks.'), ul(['Configure SDV, DDE, and signature requirements','Set up query routing','Use My Tasks effectively','Manage workflow assignments']), tip('Based on SOP-017 v6.0')),
  buildSlide(2, 'Per-Form Workflow Configuration', h2('Workflow Settings'), p('Each form can have individual workflow requirements:'), table(['Setting','Options','Effect'],[['SDV Required','Yes/No','Determines if monitor must verify'],['DDE Required','Yes/No','Enables double data entry'],['Signature Required','Yes/No','E-signature needed on submission'],['Query Routing','User/Role','Who receives auto-generated queries']]), action('Open Workflow Management and configure a form.')),
  buildSlide(3, 'My Tasks Overview', h2('Your Action Items'), p('My Tasks aggregates all pending work:'), ul(['<strong>Forms to Complete</strong> — assigned data entry','<strong>Queries to Answer</strong> — queries assigned to you','<strong>Signatures Needed</strong> — forms awaiting your signature','<strong>SDV Required</strong> — fields needing verification','<strong>DDE Discrepancies</strong> — double entry mismatches','<strong>Approvals Pending</strong> — unlock requests to review']), p('Tasks are organized by priority and due date.')),
  buildSlide(4, 'Task Types and Actions', h2('7 Task Types'), ol(['<strong>Data Entry</strong> — navigate to form, enter data, submit','<strong>Query Response</strong> — open query, respond, propose correction','<strong>E-Signature</strong> — review and sign completed form','<strong>SDV Verification</strong> — compare to source, mark verified','<strong>DDE Resolution</strong> — resolve discrepancy between entries','<strong>Approval</strong> — approve/reject unlock or change request','<strong>Review</strong> — general review task (custom)']), p('Click any task to jump directly to the relevant form/page.')),
  buildSlide(5, 'Query Routing Configuration', h2('Automatic Assignment'), p('When validation rules create queries, routing determines who receives them:'), ul(['<strong>By Role</strong> — send to all users with a specific role at the site','<strong>By User</strong> — send to a specific named user','<strong>By Form Owner</strong> — send to whoever entered the original data','<strong>Escalation</strong> — auto-escalate if unresolved after X days']), tip('Configure routing in Workflow Management → select form → Query Routing tab.')),
  buildSlide(6, 'Module Summary', h2('Key Takeaways'), ul(['Each form has configurable workflow requirements (SDV, DDE, signature)','My Tasks shows all pending work in one place','7 task types cover all workflow actions','Query routing controls who receives auto-generated queries','Tasks link directly to the relevant form/action','Configure workflows before study enrollment begins']), p('<strong>Ready for the quiz!</strong>'))
];
