import { Slide, buildSlide, h2, p, ul, ol, tip, warn, action, table } from './helpers';

export const loginNavSlides: Slide[] = [
  buildSlide(1, 'Welcome to AccuraTrial EDC', h2('Login and Navigation Training'), p('This module teaches you how to sign in and navigate the system.'), p('<strong>Learning objectives:</strong>'), ul(['Sign in with username/password or Google','Navigate the dashboard and sidebar','Find tasks, patients, forms, and reports','Manage your profile and sign out safely']), tip('AccuraTrial is 21 CFR Part 11 compliant. Always sign out when finished.')),
  buildSlide(2, 'Prerequisites', h2('What You Need'), table(['Requirement','Where to Get It'],[['Username','From your system administrator'],['Temporary Password','Given at account creation'],['Web Browser','Chrome, Edge, or Firefox (latest)'],['Internet','Stable connection required']]), tip('Bookmark the login URL for quick daily access.')),
  buildSlide(3, 'Step 1: Open the Login Page', h2('Opening AccuraTrial'), p('Navigate to the URL provided by your administrator.'), p('You will see compliance badges: <strong>HIPAA Compliant</strong> and <strong>21 CFR Part 11</strong>.'), action('Open the AccuraTrial login page in your browser now.')),
  buildSlide(4, 'Step 2: Enter Credentials', h2('Signing In'), p('Enter your username and password.'), p('<strong>Password Rules:</strong>'), ul(['Minimum 8 characters','Mix of uppercase, lowercase, numbers, symbols','Expires every 90 days','5 failed attempts = 15-minute lockout']), action('Enter your credentials and click Sign In.')),
  buildSlide(5, 'The Dashboard', h2('Your Home Screen'), p('After signing in, the Dashboard shows:'), ul(['<strong>Statistics Cards</strong> — enrollment, forms, queries at a glance','<strong>Recent Activity</strong> — latest actions','<strong>My Tasks</strong> — items requiring attention','<strong>Top Nav Bar</strong> — notifications, profile, sign-out']), p('Content varies by role.')),
  buildSlide(6, 'Sidebar Navigation', h2('Getting Around'), p('The sidebar has three sections:'), p('<strong>Main:</strong> Dashboard, My Tasks, Queries'), p('<strong>Clinical:</strong> Patients, Forms, Studies'), p('<strong>Admin:</strong> Users, Reports, Settings (admin only)'), tip('Click the collapse icon to minimize the sidebar.')),
  buildSlide(7, 'Navigating Pages', h2('Key Destinations'), ul(['<strong>My Tasks</strong> — forms to complete, queries to answer','<strong>Queries</strong> — data queries assigned to you','<strong>Patients</strong> — patient records and data entry','<strong>Forms</strong> — CRF template management','<strong>Studies</strong> — study configuration','<strong>Reports</strong> — analytics and enrollment']), action('Click through each sidebar item to explore.')),
  buildSlide(8, 'Profile and Sign Out', h2('Managing Your Session'), p('<strong>Profile:</strong> Click your name in the top-right corner.'), p('<strong>Sign Out:</strong> Always use the Sign Out button.'), warn('Never just close the browser tab. The system logs session duration for audit compliance.'), p('<strong>Session Timeout:</strong> 30 minutes of inactivity = automatic sign-out.')),
  buildSlide(9, 'Role-Based Access', h2('What You See Depends on Role'), table(['Role','Access'],[['Administrator','Full access — all menus'],['Data Manager','Patients, Tasks, Queries, Forms, Validation, Data Locks'],['Investigator','Patients, Tasks, Queries, Randomization, SDV'],['Coordinator','Patients, Tasks, Queries, Forms, Studies'],['Monitor','Patients, Tasks, SDV, Audit Logs, Reports'],['Viewer','Patients, Reports, Queries (read-only)']])),
  buildSlide(10, 'Quick-Start Tips', h2('Tips for Success'), ol(['Check My Tasks first each day','Use search to find patients/forms quickly','Watch notification badges — red means action needed','Bookmark the login URL','Save frequently during data entry']), p('<strong>Ready for the quiz!</strong>'))
];

export const userMgmtSlides: Slide[] = [
  buildSlide(1, 'Welcome to User Management', h2('User Management Training'), p('Learn to create users, assign roles, and manage permissions.'), ul(['Create and edit user accounts','Assign role-based access','Configure granular permissions','Handle access requests and invitations']), tip('Based on SOP-015 v6.0')),
  buildSlide(2, 'Navigating to User Management', h2('Finding the Users Page'), p('Click <strong>Users</strong> in the Admin section of the sidebar.'), p('The User Management page shows:'), ul(['User list with search and filters','Role indicators and status badges','Action buttons: Create, Edit, Deactivate','Permission summary per user'])),
  buildSlide(3, 'Creating a New User', h2('Adding a User Account'), ol(['Click "Create User" button','Fill in: First Name, Last Name, Email, Username','Select Role from dropdown','Set temporary password','Choose organization/site assignment','Click "Create"']), p('The user receives a welcome email with login instructions.'), warn('Never share passwords via unencrypted channels.')),
  buildSlide(4, 'System Roles', h2('Understanding Roles'), table(['Role','Level','Description'],[['Administrator','Full','Complete system access, user management'],['Data Manager','High','Form design, validation rules, data locks'],['Investigator','Clinical','Patient care, data entry, signatures'],['Coordinator','Clinical','Data entry, patient management'],['Monitor','Review','SDV, query creation, audit review'],['Viewer','Read-only','Reports and export only']])),
  buildSlide(5, 'Permission Management', h2('Granular Permissions'), p('Beyond roles, 42 individual permissions can be toggled:'), ul(['canManageUsers — create/edit user accounts','canManageForms — design CRF templates','canLockData — freeze/lock records','canManageStudies — configure studies','canViewAuditTrail — access audit logs','canExportData — download data exports']), p('Use "A La Carte" overrides to grant specific permissions beyond a role.')),
  buildSlide(6, 'Editing and Deactivating Users', h2('Managing Existing Users'), p('<strong>Editing:</strong> Click the edit icon on any user row to modify their details or role.'), p('<strong>Deactivating:</strong> Deactivated users cannot log in but their audit trail is preserved.'), warn('Per 21 CFR Part 11, never delete users — always deactivate to maintain audit integrity.'), action('Try editing a test user account.')),
  buildSlide(7, 'Access Requests and Invitations', h2('Onboarding New Users'), p('<strong>Invitation Flow:</strong>'), ol(['Admin sends invitation email with org code','User clicks link and completes registration','Admin reviews and approves the request','User gains access with assigned role']), p('<strong>Access Requests:</strong> Users can self-register and request access, pending admin approval.')),
  buildSlide(8, 'Module Summary', h2('Key Takeaways'), ul(['Only Administrators can manage users','Six roles provide graduated access levels','42 granular permissions for fine-tuned control','Never delete users — deactivate to preserve audit trails','Invitations and access requests streamline onboarding','Password policies enforced: 8+ chars, 90-day expiry, 5-attempt lockout']), p('<strong>Ready for the quiz!</strong>'))
];

export const studyMgmtSlides: Slide[] = [
  buildSlide(1, 'Welcome to Study Management', h2('Study Management Training'), p('Learn to create and configure clinical studies in AccuraTrial.'), ul(['Create studies using the 8-tab wizard','Define visits and event schedules','Configure sites and enrollment','Manage study parameters']), tip('Based on SOP-025 v7.0')),
  buildSlide(2, 'The Studies Page', h2('Navigating to Studies'), p('Click <strong>Studies</strong> in the sidebar.'), p('You will see:'), ul(['Active studies list with status indicators','Study cards showing enrollment progress','Create Study button (admin/manager only)','Study settings and configuration links'])),
  buildSlide(3, 'Creating a Study — Overview', h2('The 8-Tab Study Wizard'), p('Click "Create Study" to open the wizard with these tabs:'), ol(['<strong>Basic Info</strong> — name, protocol, phase, description','<strong>Facilities</strong> — sites and locations','<strong>Protocol</strong> — inclusion/exclusion criteria','<strong>Eligibility</strong> — screening requirements','<strong>Design</strong> — arms, groups, randomization','<strong>Visits</strong> — scheduled events/timepoints','<strong>Groups</strong> — subject groups and strata','<strong>Settings</strong> — workflow, notifications, features']), action('Open the Create Study wizard and explore each tab.')),
  buildSlide(4, 'Basic Info Tab', h2('Study Identification'), p('Required fields:'), ul(['<strong>Study Name</strong> — descriptive title','<strong>Protocol Number</strong> — unique identifier','<strong>Phase</strong> — I, II, III, or IV','<strong>Therapeutic Area</strong> — disease category','<strong>Sponsor</strong> — sponsoring organization','<strong>Start/End Dates</strong> — planned timeline']), tip('Protocol number must be unique across all studies.')),
  buildSlide(5, 'Visits and Events', h2('Defining the Schedule'), p('The Visits tab defines when data is collected:'), ul(['Add visits with name, order, and window (days from baseline)','Each visit has one or more CRF forms assigned','Visit windows define acceptable timing ranges','Unscheduled visits can be added for adverse events']), p('After creating visits, assign forms via the Event-CRF Assignment page.')),
  buildSlide(6, 'Site Management', h2('Configuring Study Sites'), p('Each study can have multiple sites:'), ol(['Add site name and location','Assign a Principal Investigator','Set enrollment target per site','Configure site-specific settings']), p('Sites appear in filters throughout the system for multi-site trials.')),
  buildSlide(7, 'Study Parameters', h2('Configuration Options'), ul(['<strong>Enrollment cap</strong> — maximum subjects allowed','<strong>Randomization</strong> — enable/configure algorithm','<strong>Blinding</strong> — single, double, or open-label','<strong>Feature flags</strong> — enable SDV, DDE, e-consent','<strong>Workflow settings</strong> — default query routing, signature requirements']), warn('Changes to study parameters after enrollment begins may require protocol amendment.')),
  buildSlide(8, 'Module Summary', h2('Key Takeaways'), ul(['Studies are created via 8-tab wizard','Each study has visits with assigned CRF forms','Sites are configured per study with enrollment targets','Study parameters control randomization, blinding, and features','Only administrators and managers can create/modify studies']), p('<strong>Ready for the quiz!</strong>'))
];
