-- ============================================================
-- ADD SECURITY AWARENESS COURSE
-- ============================================================
INSERT INTO acc_training_courses (course_code, course_name, description, version, duration_minutes, passing_score, required_for_roles, regulatory_reference, validity_period_days)
VALUES ('SECURITY', 'Security Awareness for Clinical Systems', 'Required security training covering password management, phishing recognition, device security, data handling, and incident reporting. Mandated by HIPAA §164.308(a)(5).', '1.0', 20, 80, '["admin","manager","investigator","coordinator","monitor","viewer"]'::jsonb, 'HIPAA §164.308(a)(5)', 365)
ON CONFLICT (course_code) DO NOTHING;

-- Get the security course ID
DO $$
DECLARE sec_id INTEGER;
BEGIN
  SELECT id INTO sec_id FROM acc_training_courses WHERE course_code = 'SECURITY';

  INSERT INTO acc_training_slides (course_id, title, content, slide_type, order_index, interactive_config) VALUES
  (sec_id, 'Password Security', '<h2>Protecting Your Credentials</h2><ul><li><strong>Minimum 8 characters</strong> with uppercase, lowercase, numbers, and symbols</li><li><strong>Never share</strong> your password with anyone — including IT staff</li><li><strong>Never reuse</strong> passwords across systems</li><li><strong>Change every 90 days</strong> (system enforces this)</li><li><strong>5 failed attempts</strong> = 15-minute lockout</li><li><strong>Never write down</strong> passwords on sticky notes or in plain text files</li></ul><p><strong>If you suspect your password is compromised:</strong> Change it immediately and notify your administrator.</p>', 'text', 1, NULL),
  (sec_id, 'Recognizing Phishing and Social Engineering', '<h2>Don''t Get Tricked</h2><p><strong>Red flags in emails:</strong></p><ul><li>Urgent language ("Your account will be locked in 1 hour!")</li><li>Sender address doesn''t match organization domain</li><li>Links that don''t match where they claim to go (hover to check)</li><li>Requests for credentials, patient data, or financial info</li><li>Unexpected attachments from unknown senders</li></ul><p><strong>What to do:</strong></p><ol><li>Do NOT click links or open attachments</li><li>Do NOT reply with any information</li><li>Report to your IT security team immediately</li><li>Delete the email</li></ol><p><strong>AccuraTrial will NEVER ask for your password via email.</strong></p>', 'text', 2, NULL),
  (sec_id, 'Exercise: Spot the Phishing Email', '', 'interactive', 3,
  '{"type":"scenario","instruction":"You receive an email: ''Dear User, Your AccuraTrial session has expired. Click here to verify your account immediately or lose access. - IT Support Team''. The sender is support@accura-trials-verify.com. What do you do?","data":{"context":"The email looks urgent, has the AccuraTrial name, but the sender domain is accura-trials-verify.com (not your real domain).","choices":[{"text":"Click the link quickly to avoid losing access","correct":false,"feedback":"NEVER click links in suspicious emails. The domain ''accura-trials-verify.com'' is not your real AccuraTrial domain."},{"text":"Reply asking if it is legitimate","correct":false,"feedback":"Never reply to suspicious emails — this confirms your email is active to the attacker."},{"text":"Report it to IT security and delete it — the domain is fake","correct":true,"feedback":"Correct! The sender domain is fake. Report to IT, do not click or reply, and delete."},{"text":"Forward it to your colleagues to warn them","correct":false,"feedback":"Do not forward phishing emails — this spreads the threat. Report to IT who will send a proper warning."}]},"successMessage":"You correctly identified and handled the phishing attempt!"}'),
  (sec_id, 'Device and Workstation Security', '<h2>Physical Security</h2><ul><li><strong>Lock your screen</strong> when stepping away (Win+L or Cmd+Control+Q)</li><li><strong>Never leave</strong> logged-in sessions unattended</li><li><strong>Position monitors</strong> away from public view (shoulder surfing)</li><li><strong>Secure laptops</strong> in locked drawers when not in use</li><li><strong>No USB drives</strong> with patient data unless encrypted and authorized</li><li><strong>Public WiFi</strong> — never access patient data on unsecured networks</li></ul><p><strong>Session Timeout:</strong> AccuraTrial automatically logs you out after 30 minutes of inactivity. This is a regulatory safeguard, not a bug.</p>', 'text', 4, NULL),
  (sec_id, 'Data Handling and Incident Reporting', '<h2>Handling Clinical Data Safely</h2><p><strong>DO:</strong></p><ul><li>Access only patient records relevant to your assigned studies</li><li>Use AccuraTrial''s built-in export features (encrypted, audited)</li><li>Report any suspected data breach within 1 hour</li><li>Verify recipient identity before sharing any study data</li></ul><p><strong>DO NOT:</strong></p><ul><li>Copy patient data to personal devices or cloud storage</li><li>Screenshot patient records and share via messaging apps</li><li>Discuss patient details in public spaces or on social media</li><li>Send unencrypted PHI via regular email</li></ul><p><strong>If you suspect a breach:</strong></p><ol><li>Stop the activity immediately</li><li>Report to Privacy Officer within 1 hour</li><li>Document what data was potentially exposed</li><li>Do NOT attempt to investigate independently</li></ol>', 'text', 5, NULL),
  (sec_id, 'Knowledge Check: Security', '', 'knowledge-check', 6,
  '{"sectionTitle":"Security Awareness","questions":[{"id":"sec-1","question":"AccuraTrial may ask for your password via email in emergencies.","type":"true-false","options":["True","False"],"correctIndex":1,"explanation":"AccuraTrial will NEVER ask for passwords via email. Any such request is a phishing attempt."},{"id":"sec-2","question":"What should you do if your screen will be unattended for 2 minutes?","type":"multiple-choice","options":["Leave it — 2 minutes is fine","Lock the screen (Win+L)","Log out completely","Ask a colleague to watch it"],"correctIndex":1,"explanation":"Always lock your screen when stepping away, even briefly."},{"id":"sec-3","question":"Suspected data breaches should be reported within:","type":"multiple-choice","options":["1 hour","24 hours","1 week","At the next team meeting"],"correctIndex":0,"explanation":"Report suspected breaches within 1 hour to your Privacy Officer."}]}');

  INSERT INTO acc_training_questions (course_id, question_text, question_type, options, explanation, order_index) VALUES
  (sec_id, 'Your password should be shared with your supervisor for backup access.', 'true_false', '[{"text":"True","isCorrect":false},{"text":"False","isCorrect":true}]', 'Never share passwords — each user must have their own unique credentials.', 1),
  (sec_id, 'What is the first thing to do if you receive a suspicious email?', 'multiple_choice', '[{"text":"Click the link to verify if it is real","isCorrect":false},{"text":"Reply asking for confirmation","isCorrect":false},{"text":"Do not click anything — report to IT security","isCorrect":true},{"text":"Forward to your team","isCorrect":false}]', 'Never interact with suspicious emails. Report to IT security.', 2),
  (sec_id, 'AccuraTrial logs you out after 30 minutes of inactivity because:', 'multiple_choice', '[{"text":"It is a software bug","isCorrect":false},{"text":"To save server resources","isCorrect":false},{"text":"21 CFR Part 11 regulatory requirement for session management","isCorrect":true},{"text":"Your internet connection is slow","isCorrect":false}]', 'Session timeout is a 21 CFR Part 11 security control.', 3),
  (sec_id, 'You may copy patient data to your personal Google Drive for convenience.', 'true_false', '[{"text":"True","isCorrect":false},{"text":"False","isCorrect":true}]', 'Never copy PHI to personal devices or unauthorized cloud storage.', 4),
  (sec_id, 'How quickly must a suspected data breach be reported?', 'multiple_choice', '[{"text":"Same day","isCorrect":false},{"text":"Within 1 hour","isCorrect":true},{"text":"Within 1 week","isCorrect":false},{"text":"At the next audit","isCorrect":false}]', 'Report breaches within 1 hour to the Privacy Officer.', 5);
END $$;

-- ============================================================
-- MORE HANDS-ON: Study Creation (add to course 3)
-- ============================================================
INSERT INTO acc_training_slides (course_id, title, content, slide_type, order_index, interactive_config) VALUES
(3, 'Exercise: Configure a Study Site', '', 'interactive', 13,
'{"type":"fill-form","instruction":"Add a new study site to your Phase III trial:","data":{"fields":[{"label":"Site Name","type":"text","correctAnswer":"any","placeholder":"e.g., Memorial General Hospital"},{"label":"Site Number","type":"text","correctAnswer":"any","placeholder":"e.g., SITE-003","hint":"Use format SITE-XXX"},{"label":"City","type":"text","correctAnswer":"any","placeholder":"e.g., Chicago"},{"label":"Principal Investigator","type":"dropdown","options":["Dr. Smith","Dr. Johnson","Dr. Williams","Dr. Brown"],"correctAnswer":"any"},{"label":"Enrollment Target","type":"number","correctAnswer":"any","placeholder":"e.g., 25","hint":"How many subjects this site plans to enroll"}]},"successMessage":"Site configured! In the real system, this site would now appear in all study filters.","hintMessage":"Fill in all fields with realistic values. Any non-empty entries are accepted for this practice exercise."}'),
(3, 'Exercise: Study Settings Quiz', '', 'interactive', 14,
'{"type":"scenario","instruction":"Your study requires double data entry (DDE) for all vital signs forms, SDV for all forms, and e-signatures on submission. Where do you configure these defaults?","data":{"context":"You are setting up a new study and need all forms to have DDE, SDV, and signature requirements by default.","choices":[{"text":"Configure each form individually in the Form Builder","correct":false,"feedback":"While you CAN set per-form workflows later, the default settings should be configured in the Study wizard first."},{"text":"Tab 8: Settings — set default workflow requirements (DDE, SDV, Signature all enabled)","correct":true,"feedback":"Correct! Tab 8 Settings is where you configure default workflow requirements that apply to all forms in the study."},{"text":"Tab 5: Design — in the treatment arm configuration","correct":false,"feedback":"The Design tab handles treatment arms and randomization, not workflow settings."},{"text":"After study creation, in the Workflow Management page","correct":false,"feedback":"Workflow Management allows per-form overrides, but defaults should be set during study creation in Tab 8."}]},"successMessage":"Tab 8 Settings is the right place for study-wide workflow defaults!"}');

-- ============================================================
-- MORE HANDS-ON: Patient/eCRF Data Entry (add to course 5 - DATA-ENTRY)
-- ============================================================
INSERT INTO acc_training_slides (course_id, title, content, slide_type, order_index, interactive_config) VALUES
(5, 'Exercise: Fill In a Vital Signs eCRF', '', 'interactive', 19,
'{"type":"fill-form","instruction":"Complete this Vital Signs form for a patient visit. Enter realistic clinical values:","data":{"fields":[{"label":"Systolic Blood Pressure (mmHg)","type":"number","correctAnswer":"any","placeholder":"e.g., 120","hint":"Normal range: 90-140 mmHg"},{"label":"Diastolic Blood Pressure (mmHg)","type":"number","correctAnswer":"any","placeholder":"e.g., 80","hint":"Normal range: 60-90 mmHg"},{"label":"Heart Rate (bpm)","type":"number","correctAnswer":"any","placeholder":"e.g., 72","hint":"Normal range: 60-100 bpm"},{"label":"Temperature (°C)","type":"number","correctAnswer":"any","placeholder":"e.g., 36.8","hint":"Normal range: 36.1-37.2°C"},{"label":"Weight (kg)","type":"number","correctAnswer":"any","placeholder":"e.g., 75.5"},{"label":"Respiratory Rate (breaths/min)","type":"number","correctAnswer":"any","placeholder":"e.g., 16","hint":"Normal range: 12-20"},{"label":"SpO2 (%)","type":"number","correctAnswer":"any","placeholder":"e.g., 98","hint":"Normal range: 95-100%"}]},"successMessage":"Vital signs entered! In the real system, validation rules would check these values and flag any that are out of range.","hintMessage":"Enter any realistic vital sign values. All non-empty numbers are accepted for practice."}'),
(5, 'Exercise: Handle a Yellow Warning', '', 'interactive', 20,
'{"type":"scenario","instruction":"You entered Heart Rate = 195 bpm. The system shows a YELLOW warning: ''Heart Rate 195 bpm is outside expected range (30-220). A query will be created.'' The form saves successfully. What happens next?","data":{"context":"Your form was saved. A yellow warning appeared but did not block you. Now what?","choices":[{"text":"Nothing — warnings can be ignored","correct":false,"feedback":"Incorrect! Yellow warnings create automatic queries that MUST be responded to within 48 hours."},{"text":"A query is automatically created and assigned per workflow routing. You or a reviewer must respond within 48 hours.","correct":true,"feedback":"Correct! Yellow (Create Query) warnings allow save but generate an automatic query. Someone must verify the value against source documents and respond."},{"text":"You need to go back and change the value","correct":false,"feedback":"You CAN go back and change it, but you dont HAVE to. If 195 is the real value (e.g., patient was exercising), it is valid data."},{"text":"The data manager will automatically correct it","correct":false,"feedback":"Data managers cannot change values without coordinator input. They can only create queries asking for verification."}]},"successMessage":"Yellow warnings create queries for review — they dont block data entry but require follow-up!"}'),
(5, 'Exercise: Complete an E-Signature', '', 'interactive', 21,
'{"type":"order-steps","instruction":"You finished entering data and clicked Submit & Sign. Put the e-signature steps in correct order:","data":{"steps":[{"id":"reason","text":"Select or type the reason/meaning for signing"},{"id":"modal","text":"E-signature modal appears"},{"id":"username","text":"Enter your username"},{"id":"confirm","text":"Click Confirm/Sign to complete"},{"id":"password","text":"Enter your password"},{"id":"review","text":"Review the summary of what you are signing"}],"correctOrder":["modal","review","username","password","reason","confirm"]},"successMessage":"Correct! Modal → Review → Username → Password → Reason → Confirm. Your signature is now legally binding."}');

-- ============================================================
-- MORE HANDS-ON: Patient Management (add to course 6)
-- ============================================================
INSERT INTO acc_training_slides (course_id, title, content, slide_type, order_index, interactive_config) VALUES
(6, 'Exercise: Enroll a New Patient (Full)', '', 'interactive', 18,
'{"type":"fill-form","instruction":"Complete the 3-step patient enrollment wizard:","data":{"fields":[{"label":"Step 1: Subject ID","type":"text","correctAnswer":"any","placeholder":"e.g., SITE001-042","hint":"Format: SITE-XXX where XXX is the sequential number"},{"label":"Step 2: Date of Birth","type":"date","correctAnswer":"any","placeholder":"YYYY-MM-DD"},{"label":"Step 2: Gender","type":"dropdown","options":["Male","Female","Other","Unknown"],"correctAnswer":"any"},{"label":"Step 2: Patient Initials","type":"text","correctAnswer":"any","placeholder":"e.g., JD (first + last initial)"},{"label":"Step 3: Assign to Site","type":"dropdown","options":["SITE-001 (Memorial Hospital)","SITE-002 (City Clinic)","SITE-003 (University Medical)"],"correctAnswer":"any"},{"label":"Step 3: Study Group","type":"dropdown","options":["Treatment Arm A","Treatment Arm B","Placebo","Unassigned"],"correctAnswer":"any"}]},"successMessage":"Patient enrolled! They now appear in the patient list with scheduled visits and form chips ready for data entry.","hintMessage":"Fill in all fields with realistic values. The Subject ID format and patient demographics are what coordinators enter during enrollment."}'),
(6, 'Exercise: Add an Unscheduled Visit', '', 'interactive', 19,
'{"type":"scenario","instruction":"Patient SUBJ-015 has an adverse event between Week 4 and Week 8 visits. They come in for an unplanned check-up. How do you record this?","data":{"context":"The patient had a reaction and came to the clinic outside their scheduled visit window. You need to collect vital signs and an adverse event form.","choices":[{"text":"Wait until the Week 8 visit and enter the data then","correct":false,"feedback":"Incorrect! Data must be entered contemporaneously. Waiting until Week 8 violates GCP §8.3.13 which requires timely documentation."},{"text":"Click Add Unscheduled Visit on the patient record, select date, and assign Vital Signs + AE forms","correct":true,"feedback":"Correct! Unscheduled visits capture data from unplanned clinic encounters. Assign the relevant forms and enter data immediately."},{"text":"Edit the Week 4 visit to add the extra forms","correct":false,"feedback":"Incorrect! Week 4 data should remain as-is. This is a separate clinical encounter requiring its own visit record."},{"text":"Call the data manager and ask them to handle it","correct":false,"feedback":"Coordinators have the ability to add unscheduled visits. This is a routine procedure you can do yourself."}]},"successMessage":"Add Unscheduled Visit is the correct procedure for unplanned clinical encounters!"}');
