-- CFR11-101 slides (course_id = 17)
INSERT INTO acc_training_slides (course_id, title, content, slide_type, order_index) VALUES
(17, 'What is 21 CFR Part 11?', '<h2>Electronic Records and Electronic Signatures</h2><p>21 CFR Part 11 is the FDA regulation that defines when electronic records and electronic signatures are considered trustworthy, reliable, and equivalent to paper records.</p><p><strong>Applies to:</strong></p><ul><li>Any electronic record that is created, modified, maintained, or transmitted under FDA regulations</li><li>Electronic signatures used in place of handwritten signatures</li></ul><p><strong>Key Sections:</strong></p><ul><li>§11.10 — Controls for closed systems</li><li>§11.30 — Controls for open systems</li><li>§11.50 — Signature manifestations</li><li>§11.100 — General requirements for e-signatures</li><li>§11.300 — Controls for identification codes/passwords</li></ul>', 'text', 1),
(17, 'Electronic Records Requirements', '<h2>§11.10 Controls for Closed Systems</h2><p>Organizations using electronic records must have:</p><ul><li><strong>System validation:</strong> Ensure accuracy, reliability, consistent intended performance</li><li><strong>Record protection:</strong> Ability to generate accurate and complete copies</li><li><strong>Record retention:</strong> Protect records throughout their required retention period</li><li><strong>Limited access:</strong> Only authorized individuals can use the system</li><li><strong>Audit trails:</strong> Computer-generated, time-stamped trails recording who did what and when</li><li><strong>Operational checks:</strong> Enforce sequencing of steps and events</li><li><strong>Authority checks:</strong> Verify that only authorized people perform certain actions</li><li><strong>Device checks:</strong> Verify source of data input</li></ul>', 'text', 2),
(17, 'Audit Trail Requirements', '<h2>§11.10(e) — Audit Trails</h2><p>Audit trails must be:</p><ul><li><strong>Computer-generated</strong> — not manually created</li><li><strong>Time-stamped</strong> — recording date and time of each action</li><li><strong>Independent</strong> — cannot be modified by the user being audited</li><li><strong>Retained</strong> — kept for at least as long as the electronic record</li></ul><p><strong>What must be recorded:</strong></p><ul><li>Who made the change (operator identity)</li><li>What was changed (old value → new value)</li><li>When it was changed (date/time stamp)</li><li>Why it was changed (reason for change)</li></ul><p><strong>In AccuraTrial:</strong> Every data modification automatically creates an audit trail entry. Reason-for-change is required for any post-submission correction.</p>', 'text', 3),
(17, 'Electronic Signature Requirements', '<h2>§11.50 and §11.100 — E-Signatures</h2><p><strong>Signature Manifestation (§11.50):</strong></p><ul><li>Printed name of the signer</li><li>Date and time of signing</li><li>Meaning of the signature (review, approval, responsibility, authorship)</li></ul><p><strong>General Requirements (§11.100):</strong></p><ul><li>Each e-signature is unique to one individual</li><li>Cannot be reused or reassigned to anyone else</li><li>Identity verified before establishing an e-signature</li><li>At least two distinct components (e.g., username + password)</li></ul><p><strong>Non-biometric signatures (§11.200):</strong></p><ul><li>First signing: both components (username + password)</li><li>Subsequent signings in same session: at least one component</li></ul>', 'text', 4),
(17, 'Knowledge Check: Part 11 Basics', '', 'knowledge-check', 5),
(17, 'Access Controls and System Validation', '<h2>Security and Validation</h2><p><strong>Access Controls (§11.300):</strong></p><ul><li>Unique user IDs — never shared or reassigned</li><li>Password aging — periodic expiration (AccuraTrial: 90 days)</li><li>Account lockout — after failed attempts (AccuraTrial: 5 attempts = 15 min lock)</li><li>Session timeout — automatic logoff after inactivity (AccuraTrial: 30 minutes)</li><li>Device checks — verify the source of data entry</li></ul><p><strong>System Validation (§11.10(a)):</strong></p><ul><li>Validate system ensures accuracy, reliability, and intended performance</li><li>Validate throughout the system lifecycle, not just at installation</li><li>Re-validate after significant changes</li><li>Document validation activities</li></ul>', 'text', 6);

UPDATE acc_training_slides SET interactive_config = '{"sectionTitle":"21 CFR Part 11","questions":[{"id":"cfr-1","question":"Audit trails under Part 11 must be computer-generated and time-stamped.","type":"true-false","options":["True","False"],"correctIndex":0,"explanation":"§11.10(e) requires computer-generated, time-stamped audit trails."},{"id":"cfr-2","question":"What must an e-signature manifestation include?","type":"multiple-choice","options":["Just the username","Name, date/time, and meaning of signature","Only a timestamp","A fingerprint scan"],"correctIndex":1,"explanation":"§11.50 requires printed name, date/time, and meaning (reason)."},{"id":"cfr-3","question":"Electronic signatures can be shared between team members.","type":"true-false","options":["True","False"],"correctIndex":1,"explanation":"§11.100 requires each e-signature to be unique to one individual, never reused or reassigned."}]}'
WHERE course_id = 17 AND slide_type = 'knowledge-check';

INSERT INTO acc_training_questions (course_id, question_text, question_type, options, explanation, order_index) VALUES
(17, 'What does 21 CFR Part 11 regulate?', 'multiple_choice', '[{"text":"Paper records only","isCorrect":false},{"text":"Electronic records and electronic signatures","isCorrect":true},{"text":"Clinical trial design","isCorrect":false},{"text":"Drug manufacturing","isCorrect":false}]', 'Part 11 governs electronic records and e-signatures.', 1),
(17, 'An electronic signature under Part 11 requires at least how many components?', 'multiple_choice', '[{"text":"One (password only)","isCorrect":false},{"text":"Two (e.g., username + password)","isCorrect":true},{"text":"Three","isCorrect":false},{"text":"Biometric only","isCorrect":false}]', '§11.200 requires at least two distinct identification components.', 2),
(17, 'Audit trails can be manually created by a system administrator.', 'true_false', '[{"text":"True","isCorrect":false},{"text":"False","isCorrect":true}]', 'Audit trails must be computer-generated, not manually created.', 3),
(17, 'How often must passwords expire under Part 11 best practices?', 'multiple_choice', '[{"text":"Never","isCorrect":false},{"text":"Every 30 days","isCorrect":false},{"text":"Periodically (AccuraTrial uses 90 days)","isCorrect":true},{"text":"Only when compromised","isCorrect":false}]', '§11.300 requires periodic password aging.', 4),
(17, 'System validation is only required at initial installation.', 'true_false', '[{"text":"True","isCorrect":false},{"text":"False","isCorrect":true}]', 'Validation must occur throughout the system lifecycle and after significant changes.', 5),
(17, 'What four things must an audit trail record?', 'multiple_choice', '[{"text":"Who, what, when, why","isCorrect":true},{"text":"Who, what, where, how","isCorrect":false},{"text":"What, when, how much, why","isCorrect":false},{"text":"Who, where, when, how","isCorrect":false}]', 'Audit trails must record who, what was changed, when, and why.', 6),
(17, 'E-signatures are legally equivalent to handwritten signatures under Part 11.', 'true_false', '[{"text":"True","isCorrect":true},{"text":"False","isCorrect":false}]', 'Compliant e-signatures have the same legal standing as handwritten signatures.', 7),
(17, 'Account lockout after failed login attempts is optional under Part 11.', 'true_false', '[{"text":"True","isCorrect":false},{"text":"False","isCorrect":true}]', '§11.300 requires controls to detect and report unauthorized access attempts.', 8);

-- HIPAA-101 slides (course_id = 18)
INSERT INTO acc_training_slides (course_id, title, content, slide_type, order_index) VALUES
(18, 'What is HIPAA and PHI?', '<h2>Health Insurance Portability and Accountability Act</h2><p>HIPAA protects individuals'' health information (PHI) from unauthorized disclosure.</p><p><strong>Protected Health Information (PHI):</strong> Any individually identifiable health information held or transmitted by a covered entity.</p><p><strong>The 18 HIPAA Identifiers:</strong></p><ul><li>Names, Dates (except year), Phone/Fax numbers</li><li>Email, SSN, Medical record numbers</li><li>Health plan numbers, Account numbers</li><li>Certificate/license numbers, Vehicle IDs</li><li>Device identifiers, Web URLs, IP addresses</li><li>Biometric identifiers, Photos, Any unique number</li></ul>', 'text', 1),
(18, 'Minimum Necessary Standard', '<h2>Use Only What You Need</h2><p>The <strong>Minimum Necessary Standard</strong> requires covered entities to make reasonable efforts to limit PHI access to the minimum needed to accomplish the intended purpose.</p><p><strong>In Clinical Research:</strong></p><ul><li>Only access patient data relevant to your role</li><li>Do not browse records of patients not in your studies</li><li>Export only the data fields needed for analysis</li><li>Use de-identified data when full PHI is not required</li></ul><p><strong>AccuraTrial Enforcement:</strong></p><ul><li>Role-based access controls limit what each user sees</li><li>PHI fields are marked and can be masked in exports</li><li>Audit trail tracks who accessed what data</li></ul>', 'text', 2),
(18, 'Breach Notification', '<h2>What Happens When PHI is Exposed</h2><p><strong>What is a breach?</strong> Unauthorized acquisition, access, use, or disclosure of unsecured PHI.</p><p><strong>Notification Requirements:</strong></p><ul><li><strong>Individuals:</strong> Notify affected persons within 60 days of discovery</li><li><strong>HHS:</strong> Report to Department of Health and Human Services</li><li><strong>Media:</strong> If breach affects 500+ residents of a state</li></ul><p><strong>What to do if you suspect a breach:</strong></p><ol><li>Report immediately to your Privacy Officer</li><li>Document what happened and what data was involved</li><li>Do NOT attempt to investigate or fix it yourself</li><li>Preserve all evidence</li></ol>', 'text', 3),
(18, 'Research Exceptions and Safeguards', '<h2>Using PHI for Research</h2><p><strong>Research use of PHI requires one of:</strong></p><ul><li>Patient authorization (signed consent for research use)</li><li>IRB/Privacy Board waiver of authorization</li><li>De-identified dataset (all 18 identifiers removed)</li><li>Limited data set with data use agreement</li></ul><p><strong>Technical Safeguards for PHI in EDC:</strong></p><ul><li>Encryption at rest and in transit (AES-256, TLS)</li><li>Unique user authentication</li><li>Automatic session timeout</li><li>Audit controls and access logs</li><li>Data backup and disaster recovery</li></ul><p><strong>In AccuraTrial:</strong> PHI fields are explicitly tagged. Data export can automatically strip identifiers for de-identified datasets.</p>', 'text', 4),
(18, 'Knowledge Check: HIPAA', '', 'knowledge-check', 5),
(18, 'Your Responsibilities', '<h2>What YOU Must Do</h2><ul><li><strong>Never</strong> share your login credentials</li><li><strong>Never</strong> access patient records outside your assigned studies</li><li><strong>Never</strong> discuss patient data in public areas</li><li><strong>Always</strong> lock your screen when stepping away</li><li><strong>Always</strong> report suspected breaches immediately</li><li><strong>Always</strong> use minimum necessary — access only what you need</li><li><strong>Always</strong> use secure channels for transmitting PHI</li></ul><p><strong>Penalties for violations:</strong> $100 - $50,000 per violation, up to $1.5 million per year. Criminal penalties possible for willful neglect.</p>', 'text', 6);

UPDATE acc_training_slides SET interactive_config = '{"sectionTitle":"HIPAA Basics","questions":[{"id":"hipaa-1","question":"How many identifiers make health information individually identifiable under HIPAA?","type":"multiple-choice","options":["10","14","18","22"],"correctIndex":2,"explanation":"HIPAA defines 18 specific identifiers that make health information PHI."},{"id":"hipaa-2","question":"A breach must be reported to affected individuals within what timeframe?","type":"multiple-choice","options":["24 hours","30 days","60 days","90 days"],"correctIndex":2,"explanation":"Breach notification must occur within 60 days of discovery."},{"id":"hipaa-3","question":"Research can always use PHI without patient authorization.","type":"true-false","options":["True","False"],"correctIndex":1,"explanation":"Research requires authorization, IRB waiver, de-identification, or limited data set agreement."}]}'
WHERE course_id = 18 AND slide_type = 'knowledge-check';

INSERT INTO acc_training_questions (course_id, question_text, question_type, options, explanation, order_index) VALUES
(18, 'What does PHI stand for?', 'multiple_choice', '[{"text":"Personal Health Insurance","isCorrect":false},{"text":"Protected Health Information","isCorrect":true},{"text":"Private Hospital Information","isCorrect":false},{"text":"Patient History Index","isCorrect":false}]', 'PHI = Protected Health Information.', 1),
(18, 'The minimum necessary standard means using the least PHI needed for the purpose.', 'true_false', '[{"text":"True","isCorrect":true},{"text":"False","isCorrect":false}]', 'Minimum necessary requires limiting PHI to what is needed.', 2),
(18, 'Which is NOT one of the 18 HIPAA identifiers?', 'multiple_choice', '[{"text":"Email address","isCorrect":false},{"text":"Blood type","isCorrect":true},{"text":"Social Security Number","isCorrect":false},{"text":"Medical record number","isCorrect":false}]', 'Blood type alone is not an identifier; it is a health data point.', 3),
(18, 'You may access any patient record in the system if you are curious about their condition.', 'true_false', '[{"text":"True","isCorrect":false},{"text":"False","isCorrect":true}]', 'Only access records relevant to your assigned role and studies.', 4),
(18, 'A breach affecting 500+ people in a state requires media notification.', 'true_false', '[{"text":"True","isCorrect":true},{"text":"False","isCorrect":false}]', 'Breaches of 500+ in a state require media notification.', 5),
(18, 'What should you do if you suspect a PHI breach?', 'multiple_choice', '[{"text":"Try to fix it yourself","isCorrect":false},{"text":"Report immediately to your Privacy Officer","isCorrect":true},{"text":"Ignore it if it seems minor","isCorrect":false},{"text":"Email the affected patients","isCorrect":false}]', 'Report immediately; do not attempt to investigate or fix independently.', 6),
(18, 'De-identified data still requires patient authorization to use for research.', 'true_false', '[{"text":"True","isCorrect":false},{"text":"False","isCorrect":true}]', 'De-identified data (all 18 identifiers removed) does not require authorization.', 7),
(18, 'HIPAA penalties can include criminal charges for willful neglect.', 'true_false', '[{"text":"True","isCorrect":true},{"text":"False","isCorrect":false}]', 'Willful neglect can result in criminal penalties.', 8);

-- BRANCHING slides (course_id = 19)
INSERT INTO acc_training_slides (course_id, title, content, slide_type, order_index) VALUES
(19, 'What is Branching Logic?', '<h2>Conditional Field Display</h2><p>Branching logic controls which fields appear based on the values entered in other fields. This makes forms dynamic and context-sensitive.</p><p><strong>Three capabilities:</strong></p><table><tr><th>Feature</th><th>What It Does</th></tr><tr><td>Show/Hide</td><td>Fields appear or disappear based on conditions</td></tr><tr><td>Conditional Required</td><td>Fields become required only when certain conditions are met</td></tr><tr><td>Form Linking</td><td>A value in one form triggers another form to be required</td></tr></table><p><strong>Example:</strong> Show "Pregnancy Details" section only when Gender = Female AND Age is 12-55.</p>', 'text', 1),
(19, 'The Branching Diagram', '<h2>Interactive SVG Visualization</h2><p>Navigate to <strong>Branching Logic</strong> in the sidebar. The interactive diagram shows all branching relationships:</p><ul><li><strong>Nodes</strong> = fields (colored by type)</li><li><strong>Edges</strong> = conditions connecting controlling field to dependent field</li><li><strong>Click a node</strong> to see its conditions</li><li><strong>Zoom/pan</strong> to explore complex forms</li></ul><p><strong>Color coding:</strong></p><ul><li>Blue = text/number fields</li><li>Green = dropdown/radio fields (common controllers)</li><li>Purple = conditional fields (shown/hidden by others)</li><li>Red = conditionally required fields</li></ul>', 'text', 2),
(19, 'Adding Show/Hide Conditions', '<h2>Step-by-Step</h2><ol><li>Click the <strong>Branching Logic</strong> tab for a form</li><li>Find the field you want to <strong>conditionally show</strong></li><li>Click "Add Condition" on its card</li><li><strong>Select controlling field</strong> — which field''s value determines visibility</li><li><strong>Select operator</strong> — equals, not equals, contains, greater than, etc.</li><li><strong>Enter value</strong> — what value triggers the show</li><li>Click Save</li></ol><p><strong>Multiple Conditions (OR logic):</strong> Add multiple conditions — field shows if ANY condition is true.</p><p><strong>Operators by field type:</strong></p><table><tr><th>Field Type</th><th>Operators</th></tr><tr><td>Dropdown/Radio</td><td>equals, not equals, is empty</td></tr><tr><td>Number</td><td>equals, greater than, less than, between</td></tr><tr><td>Text</td><td>equals, contains, starts with, is empty</td></tr><tr><td>Checkbox</td><td>is checked, is not checked</td></tr></table>', 'text', 3),
(19, 'Exercise: Create a Show/Hide Condition', '', 'interactive', 4),
(19, 'Conditional Required and Form Linking', '<h2>Advanced Branching</h2><p><strong>Conditional Required:</strong></p><ul><li>Make a field required ONLY when a condition is met</li><li>Example: "Pregnancy Test Date" required only when Gender = Female</li><li>Configure same way as show/hide but toggle "Required When Shown"</li></ul><p><strong>Form Linking:</strong></p><ul><li>A value in one form can trigger another form to become required</li><li>Example: If "Adverse Event Occurred" = Yes → require the AE Report form</li><li>Configure in Branching Logic → Form Linking tab</li><li>Set: Trigger Field, Trigger Value, Target Form, Required flag</li></ul><p><strong>Important:</strong> All branching rule changes require e-signature per 21 CFR Part 11.</p>', 'text', 5),
(19, 'Knowledge Check: Branching', '', 'knowledge-check', 6),
(19, 'How Branching Works at Runtime', '<h2>During Data Entry</h2><ol><li>User opens a form for data entry</li><li>System evaluates all branching conditions</li><li>Fields that don''t meet their show conditions are <strong>hidden</strong></li><li>User enters data into a controlling field</li><li>System <strong>re-evaluates</strong> conditions in real-time</li><li>Dependent fields appear/disappear instantly</li><li>Hidden fields are NOT submitted (their values are cleared)</li></ol><p><strong>Best Practices:</strong></p><ul><li>Test branching in Preview mode before publishing</li><li>Avoid circular dependencies (A shows B which shows A)</li><li>Document complex branching logic for study team</li><li>Use the diagram to verify relationships visually</li></ul>', 'text', 7);

UPDATE acc_training_slides SET interactive_config = '{"type":"scenario","instruction":"A form has a Gender field (Male/Female) and a Pregnancy Test Date field that should only appear for females. How do you configure this?","data":{"context":"You need Pregnancy Test Date to be visible only when Gender = Female.","choices":[{"text":"Add a validation rule to block save if Gender is Male and date is filled","correct":false,"feedback":"Validation rules check values after entry. Branching logic prevents the field from showing at all."},{"text":"Add a show/hide condition: Show Pregnancy Test Date when Gender equals Female","correct":true,"feedback":"Correct! Add a branching condition on the Pregnancy Test Date field with controlling field = Gender, operator = equals, value = Female."},{"text":"Create two separate forms, one for each gender","correct":false,"feedback":"This creates unnecessary duplication. Branching logic handles conditional display within a single form."},{"text":"Make it required and tell male patients to enter N/A","correct":false,"feedback":"This is poor UX and creates dirty data. Use branching to hide irrelevant fields."}]},"successMessage":"You correctly identified how to use show/hide branching!"}'
WHERE course_id = 19 AND order_index = 4;

UPDATE acc_training_slides SET interactive_config = '{"sectionTitle":"Branching Logic","questions":[{"id":"br-1","question":"Branching logic can show/hide fields based on values in other fields.","type":"true-false","options":["True","False"],"correctIndex":0,"explanation":"That is the primary purpose of branching logic."},{"id":"br-2","question":"What happens to hidden field values when the form is submitted?","type":"multiple-choice","options":["They are saved with their last value","They are cleared and not submitted","They cause a validation error","They are converted to null"],"correctIndex":1,"explanation":"Hidden fields are cleared and not included in the submission."},{"id":"br-3","question":"Multiple show conditions on a field use what logic?","type":"multiple-choice","options":["AND (all must be true)","OR (any can be true)","XOR (exactly one must be true)","NOT (none can be true)"],"correctIndex":1,"explanation":"Multiple conditions use OR logic — field shows if ANY condition is met."}]}'
WHERE course_id = 19 AND slide_type = 'knowledge-check';

INSERT INTO acc_training_questions (course_id, question_text, question_type, options, explanation, order_index) VALUES
(19, 'Branching logic shows/hides fields based on other field values.', 'true_false', '[{"text":"True","isCorrect":true},{"text":"False","isCorrect":false}]', 'Branching controls conditional field visibility.', 1),
(19, 'Hidden fields retain their values after form submission.', 'true_false', '[{"text":"True","isCorrect":false},{"text":"False","isCorrect":true}]', 'Hidden field values are cleared and not submitted.', 2),
(19, 'What operator would you use to show a field when a number is above 100?', 'multiple_choice', '[{"text":"equals","isCorrect":false},{"text":"contains","isCorrect":false},{"text":"greater than","isCorrect":true},{"text":"starts with","isCorrect":false}]', 'Use greater than for numeric comparisons.', 3),
(19, 'Form Linking allows one form to trigger another form to become required.', 'true_false', '[{"text":"True","isCorrect":true},{"text":"False","isCorrect":false}]', 'Form linking triggers requirement of another form based on a value.', 4),
(19, 'Circular dependencies in branching (A shows B, B shows A) are safe to use.', 'true_false', '[{"text":"True","isCorrect":false},{"text":"False","isCorrect":true}]', 'Circular dependencies should be avoided as they create unpredictable behavior.', 5),
(19, 'Changes to branching rules require an e-signature.', 'true_false', '[{"text":"True","isCorrect":true},{"text":"False","isCorrect":false}]', 'Per 21 CFR Part 11, branching rule changes require e-signature.', 6),
(19, 'Multiple show/hide conditions on a single field use OR logic.', 'true_false', '[{"text":"True","isCorrect":true},{"text":"False","isCorrect":false}]', 'Field shows if ANY of its conditions are met.', 7),
(19, 'Where can you visually see all branching relationships for a form?', 'multiple_choice', '[{"text":"The Design tab","isCorrect":false},{"text":"The interactive branching diagram","isCorrect":true},{"text":"The audit log","isCorrect":false},{"text":"The patient record","isCorrect":false}]', 'The interactive SVG diagram shows all branching relationships.', 8);
