-- GCP-101 slides (course_id = 16)
INSERT INTO acc_training_slides (course_id, title, content, slide_type, order_index) VALUES
(16, 'What is Good Clinical Practice?', '<h2>ICH E6(R2) GCP Overview</h2><p>Good Clinical Practice (GCP) is an international ethical and scientific quality standard for designing, conducting, recording, and reporting trials involving human subjects.</p><ul><li>Protects rights, safety, and well-being of trial subjects</li><li>Ensures clinical trial data is credible and accurate</li><li>Required by FDA, EMA, and all major regulatory agencies</li></ul><p><strong>Key Principle:</strong> The rights, safety, and well-being of the trial subjects are the most important considerations and should prevail over interests of science and society.</p>', 'text', 1),
(16, 'Investigator Responsibilities', '<h2>What Investigators Must Do</h2><ul><li><strong>Qualified:</strong> Education, training, and experience to assume responsibility for the trial</li><li><strong>Adequate resources:</strong> Sufficient time, staff, facilities, and equipment</li><li><strong>Medical care:</strong> Responsible for all trial-related medical decisions</li><li><strong>Protocol compliance:</strong> Conduct trial per the approved protocol</li><li><strong>Informed consent:</strong> Obtain consent before any trial-related procedure</li><li><strong>Record keeping:</strong> Maintain adequate and accurate source documents</li><li><strong>Safety reporting:</strong> Report serious adverse events within 24 hours</li></ul>', 'text', 2),
(16, 'Informed Consent Requirements', '<h2>ICH E6 Section 4.8</h2><p>Informed consent must be:</p><ul><li>Obtained <strong>before</strong> any study-related procedure</li><li>Given freely without coercion or undue influence</li><li>Written in language the subject can understand</li><li>Signed and dated by the subject (or legally authorized representative)</li></ul><p><strong>Required Elements:</strong></p><ul><li>Statement that the study involves research</li><li>Purpose, duration, and procedures</li><li>Foreseeable risks and discomforts</li><li>Expected benefits</li><li>Alternative treatments available</li><li>Confidentiality of records</li><li>Compensation and treatment for injury</li><li>Voluntary participation with right to withdraw</li></ul>', 'text', 3),
(16, 'Essential Documents', '<h2>ICH E6 Section 8</h2><p>Essential documents are those which individually and collectively permit evaluation of the conduct of a trial and quality of data produced.</p><p><strong>Before Trial:</strong></p><ul><li>Investigator Brochure, Protocol, Informed Consent Forms</li><li>IRB/IEC approval, Financial disclosures</li><li>CVs and training records of staff</li></ul><p><strong>During Trial:</strong></p><ul><li>Signed consent forms, Source documents</li><li>CRF pages (electronic or paper)</li><li>Monitoring visit reports, AE reports</li></ul><p><strong>After Trial:</strong></p><ul><li>Final report, Audit certificates</li><li>Treatment allocation records</li><li>Retained for minimum 2 years after last approval or formal discontinuation</li></ul>', 'text', 4),
(16, 'Knowledge Check: GCP Basics', '', 'knowledge-check', 5),
(16, 'Record Retention and Protocol Deviations', '<h2>Compliance Requirements</h2><p><strong>Record Retention:</strong></p><ul><li>Retain essential documents for at least 2 years after last marketing approval in an ICH region</li><li>Or 2 years after formal discontinuation of clinical development</li><li>Longer if required by applicable regulations or sponsor agreement</li></ul><p><strong>Protocol Deviations:</strong></p><ul><li>Document and report all deviations from the approved protocol</li><li>Implement only after IRB/IEC approval (except for immediate safety)</li><li>Emergency deviations to protect subjects must be documented and reported</li></ul>', 'text', 6);

-- GCP-101 knowledge check config
UPDATE acc_training_slides SET interactive_config = '{"sectionTitle":"GCP Fundamentals","questions":[{"id":"gcp-1","question":"What is the primary purpose of GCP?","type":"multiple-choice","options":["Speed up drug approval","Protect trial subject rights, safety, and well-being","Reduce trial costs","Simplify regulatory submissions"],"correctIndex":1,"explanation":"GCP exists primarily to protect the rights, safety, and well-being of trial subjects."},{"id":"gcp-2","question":"Informed consent must be obtained before any study-related procedure.","type":"true-false","options":["True","False"],"correctIndex":0,"explanation":"ICH E6 Section 4.8 requires consent before any study-related procedure."},{"id":"gcp-3","question":"How long must essential documents be retained after the last marketing approval?","type":"multiple-choice","options":["6 months","1 year","At least 2 years","5 years"],"correctIndex":2,"explanation":"ICH E6 requires retention for at least 2 years after last approval or formal discontinuation."}]}'
WHERE course_id = 16 AND slide_type = 'knowledge-check';

-- GCP-101 quiz questions
INSERT INTO acc_training_questions (course_id, question_text, question_type, options, explanation, order_index) VALUES
(16, 'Who is ultimately responsible for medical care of trial subjects?', 'multiple_choice', '[{"text":"The sponsor","isCorrect":false},{"text":"The CRO","isCorrect":false},{"text":"The principal investigator","isCorrect":true},{"text":"The IRB/IEC","isCorrect":false}]', 'Per ICH E6 Section 4.3, the investigator is responsible for medical care.', 1),
(16, 'Informed consent can be obtained verbally without written documentation.', 'true_false', '[{"text":"True","isCorrect":false},{"text":"False","isCorrect":true}]', 'ICH E6 requires written, signed, and dated informed consent.', 2),
(16, 'Which documents are considered essential for a clinical trial?', 'multiple_choice', '[{"text":"Only the protocol","isCorrect":false},{"text":"Only signed consent forms","isCorrect":false},{"text":"All documents that permit evaluation of trial conduct and data quality","isCorrect":true},{"text":"Only financial disclosures","isCorrect":false}]', 'Essential documents collectively permit evaluation of trial conduct.', 3),
(16, 'A serious adverse event must be reported within what timeframe?', 'multiple_choice', '[{"text":"1 week","isCorrect":false},{"text":"24 hours","isCorrect":true},{"text":"30 days","isCorrect":false},{"text":"At the next monitoring visit","isCorrect":false}]', 'Serious adverse events require reporting within 24 hours.', 4),
(16, 'Protocol deviations for immediate subject safety do not need documentation.', 'true_false', '[{"text":"True","isCorrect":false},{"text":"False","isCorrect":true}]', 'Even emergency deviations must be documented and reported to IRB/IEC.', 5),
(16, 'Clinical trial records can be destroyed once the study is complete.', 'true_false', '[{"text":"True","isCorrect":false},{"text":"False","isCorrect":true}]', 'Records must be retained for at least 2 years after last approval or discontinuation.', 6),
(16, 'Which is NOT a requirement for valid informed consent?', 'multiple_choice', '[{"text":"Given freely without coercion","isCorrect":false},{"text":"Written in language subject understands","isCorrect":false},{"text":"Signed by two witnesses","isCorrect":true},{"text":"Signed and dated by subject","isCorrect":false}]', 'Two witnesses are not always required; the key requirements are free choice, understandable language, and subject signature.', 7),
(16, 'The investigator must have sufficient time, staff, and facilities for the trial.', 'true_false', '[{"text":"True","isCorrect":true},{"text":"False","isCorrect":false}]', 'ICH E6 requires investigators to have adequate resources.', 8);
