-- Delete existing BRANCHING slides and replace with comprehensive content
DELETE FROM acc_training_slides WHERE course_id = 19;
DELETE FROM acc_training_questions WHERE course_id = 19;

INSERT INTO acc_training_slides (course_id, title, content, slide_type, order_index) VALUES
(19, 'What is Branching Logic?', '<h2>Making Forms Dynamic</h2><p>Branching logic controls which fields appear based on values in other fields. This creates smart, context-sensitive forms.</p><table><tr><th>Capability</th><th>What It Does</th><th>Example</th></tr><tr><td><strong>Show/Hide</strong></td><td>Fields appear/disappear based on conditions</td><td>Show "Pregnancy Details" only when Gender = Female</td></tr><tr><td><strong>Conditional Required</strong></td><td>Fields become mandatory only when conditions met</td><td>"Specify Other" required only when Dropdown = "Other"</td></tr><tr><td><strong>Form Linking</strong></td><td>A value triggers another form to become required</td><td>AE Occurred = Yes → AE Report form required</td></tr></table><p><strong>Key Difference from Validation Rules:</strong> Validation checks values AFTER entry. Branching controls what fields APPEAR before entry.</p>', 'text', 1),
(19, 'The Branching Diagram (Interactive SVG)', '<h2>Visualizing Field Relationships</h2><p>Navigate to <strong>Branching Logic</strong> in the sidebar. Select a form to see the interactive diagram.</p><p><strong>Diagram Elements:</strong></p><ul><li><strong>Nodes</strong> = fields (circles colored by type)</li><li><strong>Edges</strong> = condition arrows (controlling → dependent)</li><li><strong>Blue nodes</strong> = text/number fields</li><li><strong>Green nodes</strong> = dropdown/radio fields (common controllers)</li><li><strong>Purple nodes</strong> = conditional fields (shown/hidden by others)</li><li><strong>Red nodes</strong> = conditionally required fields</li></ul><p><strong>Interactions:</strong></p><ul><li>Click any node → see its conditions in detail panel</li><li>Zoom/pan to explore complex relationships</li><li>Hover edge → see the condition (e.g., "When Gender = Female")</li><li>Click "Expand All" to see full form structure</li></ul><p><strong>Use the diagram to:</strong> Verify no circular dependencies, understand complex multi-level branching, document logic for study team.</p>', 'text', 2),
(19, 'The Field Card View', '<h2>Configuring Branching Per Field</h2><p>Below the diagram, each field appears as a card (same as Validation Rules view but for branching).</p><p><strong>Each card shows:</strong></p><ul><li>Field name and type badge</li><li>Current conditions count ("2 conditions" or "No conditions")</li><li>"Add Condition" button</li><li>List of existing conditions with edit/delete</li></ul><p><strong>Two sections per field:</strong></p><ol><li><strong>Show/Hide Conditions</strong> — when does this field appear?</li><li><strong>Required When</strong> — when is this field mandatory?</li></ol><p>Fields with no conditions are always visible and follow their static required setting from the form builder.</p>', 'text', 3),
(19, 'Adding Show/Hide Conditions: Step by Step', '<h2>Making a Field Conditional</h2><ol><li>Find the field you want to <strong>conditionally show</strong></li><li>Click <strong>"Add Condition"</strong> on its card</li><li><strong>Part 1:</strong> Select the <strong>controlling field</strong> — whose value determines visibility</li><li><strong>Part 2:</strong> Select the <strong>operator</strong></li><li><strong>Part 3:</strong> Enter the <strong>trigger value</strong></li><li>Click Save</li></ol><p><strong>Operators by Field Type:</strong></p><table><tr><th>Controlling Field Type</th><th>Available Operators</th></tr><tr><td>Dropdown / Radio</td><td>equals, not equals, is empty, is not empty</td></tr><tr><td>Number</td><td>equals, not equals, greater than, less than, between, is empty</td></tr><tr><td>Text</td><td>equals, not equals, contains, starts with, ends with, is empty</td></tr><tr><td>Checkbox</td><td>is checked, is not checked</td></tr><tr><td>Date</td><td>equals, before, after, between, is empty</td></tr><tr><td>Yes/No</td><td>equals Yes, equals No, is empty</td></tr></table>', 'text', 4),
(19, 'Exercise: Create a Gender-Based Condition', '', 'interactive', 5),
(19, 'Multiple Conditions (OR Logic)', '<h2>Complex Visibility Rules</h2><p>A field can have <strong>multiple conditions</strong>. The field shows if <strong>ANY</strong> condition is true (OR logic).</p><p><strong>Example:</strong> Show "Cardiovascular History" section when:</p><ul><li>Condition 1: "Medical History" includes "Heart Disease" <strong>OR</strong></li><li>Condition 2: Age > 65 <strong>OR</strong></li><li>Condition 3: "Family History of CVD" = Yes</li></ul><p>The section appears if ANY of these three conditions is met.</p><p><strong>Adding multiple conditions:</strong></p><ol><li>Add first condition (as above)</li><li>Click "Add Another Condition" (+ button)</li><li>Configure second condition on a different controlling field</li><li>Repeat for additional conditions</li></ol><p><strong>Important:</strong> Multiple conditions on the SAME field = OR. There is no AND logic within a single field''s show conditions. For AND logic, use nested branching (field A shows field B, field B shows field C).</p>', 'text', 6),
(19, 'Knowledge Check: Show/Hide Basics', '', 'knowledge-check', 7),
(19, 'Conditional Required', '<h2>Fields Required Only Sometimes</h2><p>A field can be marked as "Required When Shown" — it becomes mandatory only when its visibility condition is met.</p><p><strong>Setup:</strong></p><ol><li>First, add a Show/Hide condition (makes field conditional)</li><li>Toggle "Required When Shown" on the field card</li><li>Result: field is both conditionally visible AND conditionally required</li></ol><p><strong>Common Use Cases:</strong></p><table><tr><th>Scenario</th><th>Condition</th><th>Required Field</th></tr><tr><td>Pregnancy</td><td>Gender = Female AND Age 12-55</td><td>Pregnancy Test Date (required)</td></tr><tr><td>Other specify</td><td>Dropdown = "Other"</td><td>Specify Other text field (required)</td></tr><tr><td>AE details</td><td>AE Severity = "Serious"</td><td>SAE Report Date (required)</td></tr><tr><td>Concomitant meds</td><td>Taking Medications = Yes</td><td>Medication Name (required)</td></tr></table><p><strong>Behavior during data entry:</strong> If condition is not met → field hidden → not required → not submitted.</p>', 'text', 8),
(19, 'Form Linking', '<h2>Triggering Other Forms</h2><p>Form Linking makes one form trigger ANOTHER form to become required based on a value.</p><p><strong>Configuration (Branching Logic → Form Linking tab):</strong></p><ol><li><strong>Source Form:</strong> The form containing the trigger field</li><li><strong>Trigger Field:</strong> Which field in the source form</li><li><strong>Trigger Value:</strong> What value activates the link</li><li><strong>Target Form:</strong> Which form becomes required</li><li><strong>Required:</strong> Toggle — target form becomes required (not just available)</li></ol><p><strong>Examples:</strong></p><table><tr><th>Source Form</th><th>Trigger</th><th>Target Form</th></tr><tr><td>Adverse Events</td><td>AE Occurred = Yes</td><td>AE Detail Report (required)</td></tr><tr><td>Vital Signs</td><td>SBP > 180</td><td>Hypertension Follow-up (required)</td></tr><tr><td>Lab Results</td><td>Any value out of range</td><td>Lab Recheck form (available)</td></tr><tr><td>Screening</td><td>All criteria met = Yes</td><td>Enrollment form (required)</td></tr></table><p><strong>Important:</strong> Form links are evaluated in real-time during data entry. When the trigger value is entered, the target form appears in the patient''s visit schedule.</p>', 'text', 9),
(19, 'Exercise: Configure Form Linking', '', 'interactive', 10),
(19, 'How Branching Works During Data Entry', '<h2>Runtime Behavior</h2><ol><li>User opens a form → system evaluates ALL branching conditions</li><li>Fields not meeting conditions are <strong>hidden</strong> (not visible at all)</li><li>User enters/changes a controlling field value</li><li>System <strong>re-evaluates instantly</strong> — dependent fields appear/disappear</li><li>If a field is hidden, its value is <strong>cleared and not submitted</strong></li><li>If a conditionally required field is visible, it must be filled before submit</li></ol><p><strong>What users see:</strong></p><ul><li>Fields slide in/out smoothly as conditions change</li><li>Required indicators (red asterisk) appear on conditionally required fields</li><li>No indication of what conditions exist (transparent to end users)</li></ul><p><strong>Data implications:</strong></p><ul><li>Hidden field values are NEVER stored in the database</li><li>If a user fills a field, then changes the controlling field to hide it, the data is lost</li><li>Audit trail records show/hide transitions</li></ul>', 'text', 11),
(19, 'Best Practices and Troubleshooting', '<h2>Branching Do''s and Don''ts</h2><p><strong>DO:</strong></p><ul><li>Test branching in Preview mode before publishing</li><li>Use the diagram to verify relationships visually</li><li>Document complex branching for the study team</li><li>Keep branching depth shallow (max 2-3 levels)</li><li>Use dropdown/radio fields as controllers (most intuitive)</li></ul><p><strong>DON''T:</strong></p><ul><li>Create circular dependencies (A shows B, B shows A)</li><li>Branch on calculated fields (values change unpredictably)</li><li>Create deep nesting (A→B→C→D→E) — hard to debug</li><li>Forget to test edge cases (what if controlling field is empty?)</li></ul><p><strong>Troubleshooting:</strong></p><table><tr><th>Problem</th><th>Cause</th><th>Fix</th></tr><tr><td>Field won''t show</td><td>Condition value doesn''t match exactly</td><td>Check exact spelling/casing of trigger value</td></tr><tr><td>Field always shows</td><td>Condition uses "is not empty" on a pre-filled field</td><td>Change to specific value match</td></tr><tr><td>Data disappearing</td><td>User changes controlling field after filling dependent</td><td>Document this behavior for CRCs; consider moving controller earlier in form</td></tr></table>', 'text', 12),
(19, 'Knowledge Check: Advanced Branching', '', 'knowledge-check', 13);

-- BRANCHING exercise configs
UPDATE acc_training_slides SET interactive_config = '{"type":"fill-form","instruction":"Configure a show/hide condition: Show ''Pregnancy Test Date'' when Gender = Female","data":{"fields":[{"label":"Dependent Field (to show/hide)","type":"dropdown","options":["Pregnancy Test Date","Patient Age","Weight","Blood Type"],"correctAnswer":"Pregnancy Test Date"},{"label":"Controlling Field","type":"dropdown","options":["Gender","Age","Weight","Study Site"],"correctAnswer":"Gender"},{"label":"Operator","type":"dropdown","options":["equals","not equals","greater than","contains"],"correctAnswer":"equals"},{"label":"Trigger Value","type":"dropdown","options":["Male","Female","Other","Unknown"],"correctAnswer":"Female"}]},"successMessage":"Correct! Pregnancy Test Date shows when Gender equals Female.","hintMessage":"The dependent field is Pregnancy Test Date, controlled by Gender, operator equals, value Female."}'
WHERE course_id = 19 AND order_index = 5;

UPDATE acc_training_slides SET interactive_config = '{"type":"scenario","instruction":"You need to make the AE Detail Report form required whenever ''Adverse Event Occurred'' = Yes in the Visit form. How do you configure this?","data":{"context":"The Visit form has a Yes/No field called Adverse Event Occurred. When Yes is selected, you want the AE Detail Report form to automatically become required for this patient visit.","choices":[{"text":"Add a validation rule on Adverse Event Occurred","correct":false,"feedback":"Validation rules check values but cannot trigger other forms. You need Form Linking."},{"text":"Go to Branching Logic → Form Linking → set trigger field = Adverse Event Occurred, value = Yes, target = AE Detail Report","correct":true,"feedback":"Correct! Form Linking in Branching Logic connects fields in one form to requirements in another form."},{"text":"Add the AE Detail Report as required for all visits","correct":false,"feedback":"This would require it even when no AE occurred — unnecessary burden on coordinators."},{"text":"Create a workflow task to remind coordinators","correct":false,"feedback":"Manual reminders are unreliable. Form Linking automates the requirement based on the data."}]},"successMessage":"Form Linking is the correct approach for triggering forms based on field values!"}'
WHERE course_id = 19 AND order_index = 10;

-- BRANCHING knowledge check configs
UPDATE acc_training_slides SET interactive_config = '{"sectionTitle":"Show/Hide Conditions","questions":[{"id":"br-kc1","question":"Multiple show conditions on a single field use what logic?","type":"multiple-choice","options":["AND (all must be true)","OR (any can be true)","XOR (exactly one)","Depends on configuration"],"correctIndex":1,"explanation":"Multiple conditions use OR logic — field shows if ANY condition is met."},{"id":"br-kc2","question":"What operators are available for a Dropdown controlling field?","type":"multiple-choice","options":["Greater than, less than, between","Equals, not equals, is empty, is not empty","Contains, starts with, regex","Only equals"],"correctIndex":1,"explanation":"Dropdown/radio fields support equals, not equals, is empty, is not empty."},{"id":"br-kc3","question":"Hidden fields retain their values in the database.","type":"true-false","options":["True","False"],"correctIndex":1,"explanation":"Hidden field values are cleared and never submitted to the database."}]}'
WHERE course_id = 19 AND order_index = 7;

UPDATE acc_training_slides SET interactive_config = '{"sectionTitle":"Advanced Branching","questions":[{"id":"br-kc4","question":"Form Linking can make another form become required based on a field value.","type":"true-false","options":["True","False"],"correctIndex":0,"explanation":"Form Linking triggers other forms to become required based on values."},{"id":"br-kc5","question":"Circular branching dependencies (A shows B, B shows A) are safe.","type":"true-false","options":["True","False"],"correctIndex":1,"explanation":"Circular dependencies cause unpredictable behavior and must be avoided."},{"id":"br-kc6","question":"When should you use Conditional Required?","type":"multiple-choice","options":["Always make all fields required","When a field should only be mandatory under certain conditions","Never — use validation rules instead","Only for date fields"],"correctIndex":1,"explanation":"Conditional Required makes fields mandatory only when their show condition is met."}]}'
WHERE course_id = 19 AND order_index = 13;

-- BRANCHING quiz questions (10 questions)
INSERT INTO acc_training_questions (course_id, question_text, question_type, options, explanation, order_index) VALUES
(19, 'What is the primary purpose of branching logic?', 'multiple_choice', '[{"text":"Validate data after entry","isCorrect":false},{"text":"Control which fields appear based on other field values","isCorrect":true},{"text":"Calculate field values automatically","isCorrect":false},{"text":"Export data to external systems","isCorrect":false}]', 'Branching controls conditional field visibility.', 1),
(19, 'Multiple show/hide conditions on one field use OR logic.', 'true_false', '[{"text":"True","isCorrect":true},{"text":"False","isCorrect":false}]', 'Field shows if ANY condition is met.', 2),
(19, 'What happens to a field value when its show condition becomes false?', 'multiple_choice', '[{"text":"Value is preserved but field is hidden","isCorrect":false},{"text":"Value is cleared and not submitted","isCorrect":true},{"text":"Value causes an error","isCorrect":false},{"text":"Nothing changes","isCorrect":false}]', 'Hidden field values are cleared and excluded from submission.', 3),
(19, 'Which field type is most commonly used as a branching controller?', 'multiple_choice', '[{"text":"Textarea","isCorrect":false},{"text":"File upload","isCorrect":false},{"text":"Dropdown or Radio buttons","isCorrect":true},{"text":"Signature","isCorrect":false}]', 'Dropdown/radio have discrete values making them ideal controllers.', 4),
(19, 'Form Linking connects a field value in one form to requirements in another form.', 'true_false', '[{"text":"True","isCorrect":true},{"text":"False","isCorrect":false}]', 'Form Linking triggers other forms based on field values.', 5),
(19, 'Circular branching dependencies should be avoided.', 'true_false', '[{"text":"True","isCorrect":true},{"text":"False","isCorrect":false}]', 'Circular dependencies create unpredictable behavior.', 6),
(19, 'The branching diagram uses what color for conditionally-shown fields?', 'multiple_choice', '[{"text":"Blue","isCorrect":false},{"text":"Green","isCorrect":false},{"text":"Purple","isCorrect":true},{"text":"Red","isCorrect":false}]', 'Purple nodes represent conditional fields in the SVG diagram.', 7),
(19, 'A patient enters Gender=Male. Pregnancy Test Date has condition Gender=Female. What happens?', 'multiple_choice', '[{"text":"Field shows but is not required","isCorrect":false},{"text":"Field is completely hidden","isCorrect":true},{"text":"Field shows with a warning","isCorrect":false},{"text":"An error appears","isCorrect":false}]', 'Condition not met → field hidden entirely.', 8),
(19, 'Branching rule changes require an electronic signature.', 'true_false', '[{"text":"True","isCorrect":true},{"text":"False","isCorrect":false}]', 'Per 21 CFR Part 11, branching changes require e-signature.', 9),
(19, 'What is the recommended maximum branching depth?', 'multiple_choice', '[{"text":"1 level only","isCorrect":false},{"text":"2-3 levels maximum","isCorrect":true},{"text":"10+ levels for complex forms","isCorrect":false},{"text":"No limit","isCorrect":false}]', 'Keep branching depth shallow (2-3 levels) for maintainability.', 10);
