-- Add AI section to VAL-RULES (insert after existing slides)
INSERT INTO acc_training_slides (course_id, title, content, slide_type, order_index, interactive_config) VALUES
(7, 'AI Rule Suggester: Hands-On', '<h2>Using AI to Generate Rules</h2><p>The AI Suggester is accessible from every field card (sparkle/AI button). Here''s exactly how it works:</p><ol><li>Click the <strong>AI sparkle icon</strong> on any field card</li><li>Modal opens showing field context (name, type, existing rules)</li><li>AI generates 2-5 suggestions with confidence percentages</li><li>Each suggestion shows: rule type, range/pattern, severity, message</li><li>Click <strong>Accept</strong> to create the rule instantly</li><li>Click <strong>Modify</strong> to adjust before creating</li><li>Click <strong>Reject</strong> to skip that suggestion</li></ol><p><strong>What AI considers:</strong></p><ul><li>Field name semantics (e.g., "Heart Rate" → vital sign range)</li><li>Field data type (number → range check, text → format check)</li><li>Other fields in the form (cross-field comparisons)</li><li>Common clinical data patterns from training data</li></ul><p><strong>Best used for:</strong> New forms where you want a quick starting set of rules. Review each suggestion critically — AI may suggest ranges that don''t match your protocol.</p>', 'text', 16),
(7, 'Exercise: Use AI to Suggest Rules', '', 'interactive', 17,
'{"type":"scenario","instruction":"You just created a new Vital Signs form with fields: Systolic BP, Diastolic BP, Heart Rate, Temperature, Weight. You click the AI button on the Systolic BP field. What should you expect?","data":{"context":"The AI Suggester modal opens for Systolic Blood Pressure (Number field).","choices":[{"text":"AI suggests a text format check (email pattern)","correct":false,"feedback":"Incorrect. AI recognizes this is a numeric vital sign field, not a text field. It would suggest range checks."},{"text":"AI suggests range 60-250 mmHg with Create Query severity and a cross-field check that SBP > DBP","correct":true,"feedback":"Correct! AI recognizes systolic BP as a vital sign, suggests appropriate clinical range, and identifies the cross-field relationship with diastolic BP."},{"text":"AI suggests making the field required only","correct":false,"feedback":"While AI might include a required check, it would primarily suggest clinical range validation for a vital sign field."},{"text":"AI cannot analyze vital sign fields","correct":false,"feedback":"AI is especially good at vital sign fields because they have well-established clinical ranges."}]},"successMessage":"AI excels at suggesting clinically appropriate ranges and cross-field checks for vital signs!"}');

-- ============================================================
-- STUDY-MGMT: Replace with comprehensive detailed content
-- ============================================================
DELETE FROM acc_training_slides WHERE course_id = 3;
DELETE FROM acc_training_questions WHERE course_id = 3;

INSERT INTO acc_training_slides (course_id, title, content, slide_type, order_index, interactive_config) VALUES
(3, 'Study Management Overview', '<h2>Creating and Configuring Clinical Studies</h2><p>Every clinical trial in AccuraTrial starts with study creation. The 8-tab wizard guides you through all configuration.</p><p><strong>What you''ll learn:</strong></p><ul><li>Navigate to Studies and create a new study</li><li>Configure all 8 wizard tabs</li><li>Define visit schedules and assign forms</li><li>Set up sites and enrollment targets</li><li>Configure study-level settings</li></ul><p><strong>Who can create studies:</strong> Administrators and Data Managers only.</p>', 'text', 1, NULL),
(3, 'The 8-Tab Study Creation Wizard', '<h2>Wizard Structure</h2><table><tr><th>#</th><th>Tab</th><th>What You Configure</th></tr><tr><td>1</td><td><strong>Basic Info</strong></td><td>Study name, protocol number, phase, therapeutic area, sponsor, dates</td></tr><tr><td>2</td><td><strong>Facilities</strong></td><td>Sites, locations, PIs, enrollment targets per site</td></tr><tr><td>3</td><td><strong>Protocol</strong></td><td>Inclusion/exclusion criteria, protocol summary</td></tr><tr><td>4</td><td><strong>Eligibility</strong></td><td>Screening requirements, age/gender criteria</td></tr><tr><td>5</td><td><strong>Design</strong></td><td>Treatment arms, groups, randomization ratio</td></tr><tr><td>6</td><td><strong>Visits</strong></td><td>Scheduled visits/events, timing windows, visit order</td></tr><tr><td>7</td><td><strong>Groups</strong></td><td>Subject groups, strata for randomization</td></tr><tr><td>8</td><td><strong>Settings</strong></td><td>Workflow defaults, feature flags, notifications</td></tr></table><p>You can navigate between tabs freely and save progress at any point.</p>', 'text', 2, NULL),
(3, 'Tab 1: Basic Info — In Detail', '<h2>Study Identification</h2><p><strong>Required fields:</strong></p><ul><li><strong>Study Name</strong> — descriptive title (e.g., "CARDIO-2026 Phase III Heart Failure Trial")</li><li><strong>Protocol Number</strong> — unique identifier matching your protocol document (e.g., "PROT-2026-001")</li><li><strong>Phase</strong> — Phase I, II, III, or IV</li><li><strong>Therapeutic Area</strong> — Cardiology, Oncology, Neurology, Infectious Disease, etc.</li><li><strong>Sponsor</strong> — sponsoring organization name</li><li><strong>Planned Start Date</strong> and <strong>Planned End Date</strong></li></ul><p><strong>Optional fields:</strong></p><ul><li>Study Description / Synopsis</li><li>Target Enrollment (total subjects)</li><li>ClinicalTrials.gov Identifier (NCT number)</li><li>IND/IDE Number</li></ul>', 'text', 3, NULL),
(3, 'Exercise: Fill in Study Basic Info', '', 'interactive', 4,
'{"type":"fill-form","instruction":"Create a Phase III Oncology study. Fill in the Basic Info tab:","data":{"fields":[{"label":"Study Name","type":"text","correctAnswer":"any","placeholder":"e.g., ONCO-2026 Phase III Breast Cancer Trial"},{"label":"Protocol Number","type":"text","correctAnswer":"any","placeholder":"e.g., PROT-2026-042"},{"label":"Phase","type":"dropdown","options":["Phase I","Phase II","Phase III","Phase IV"],"correctAnswer":"Phase III"},{"label":"Therapeutic Area","type":"dropdown","options":["Cardiology","Oncology","Neurology","Infectious Disease","Dermatology","Endocrinology"],"correctAnswer":"Oncology"},{"label":"Planned Start Date","type":"date","correctAnswer":"any","placeholder":"YYYY-MM-DD"}]},"successMessage":"Study Basic Info configured! In the real system, you would proceed to the Facilities tab.","hintMessage":"Select Phase III and Oncology as specified in the instructions."}'),
(3, 'Tab 2: Facilities (Sites)', '<h2>Configuring Study Sites</h2><p>Each study can have multiple investigational sites:</p><p><strong>Per site, configure:</strong></p><ul><li><strong>Site Name</strong> — institution or clinic name</li><li><strong>Site Number</strong> — unique site identifier (e.g., "SITE-001")</li><li><strong>Location</strong> — city, state, country</li><li><strong>Principal Investigator</strong> — select from registered users</li><li><strong>Enrollment Target</strong> — planned subjects for this site</li><li><strong>Status</strong> — Active, Inactive, Closed</li></ul><p><strong>Adding sites:</strong> Click "Add Site" → fill details → Save. Repeat for each location.</p><p><strong>Impact:</strong> Sites appear in all filters throughout the system. Patient enrollment, randomization, and monitoring are site-aware.</p>', 'text', 5, NULL),
(3, 'Tabs 3-4: Protocol and Eligibility', '<h2>Study Criteria</h2><p><strong>Tab 3 — Protocol:</strong></p><ul><li>Upload or link protocol document</li><li>Enter inclusion criteria (numbered list)</li><li>Enter exclusion criteria (numbered list)</li><li>Protocol version and date</li></ul><p><strong>Tab 4 — Eligibility:</strong></p><ul><li>Age range (min/max)</li><li>Gender eligibility (Male/Female/Both)</li><li>Screening window (days from consent to enrollment)</li><li>Required screening procedures checklist</li></ul><p>These criteria are displayed during patient enrollment to help coordinators verify eligibility before enrolling.</p>', 'text', 6, NULL),
(3, 'Tab 5-6: Design and Visits', '<h2>Study Arms and Visit Schedule</h2><p><strong>Tab 5 — Design:</strong></p><ul><li>Number of treatment arms (e.g., Active Drug vs Placebo)</li><li>Arm names and descriptions</li><li>Randomization ratio (e.g., 2:1, 1:1:1 for 3 arms)</li><li>Blinding type (Open, Single-blind, Double-blind)</li></ul><p><strong>Tab 6 — Visits (Most Important Tab):</strong></p><p>Define every scheduled visit:</p><table><tr><th>Setting</th><th>Description</th></tr><tr><td>Visit Name</td><td>e.g., "Screening", "Baseline", "Week 4", "Week 12", "End of Study"</td></tr><tr><td>Visit Order</td><td>Sequential number (1, 2, 3...)</td></tr><tr><td>Target Day</td><td>Days from baseline (Day 0, Day 28, Day 84...)</td></tr><tr><td>Window (±days)</td><td>Acceptable range (e.g., Day 28 ± 3 days)</td></tr><tr><td>Required</td><td>Whether visit is mandatory or optional</td></tr></table><p>After creating visits, you assign CRF forms to each visit via Event-CRF Assignment.</p>', 'text', 7, NULL),
(3, 'Exercise: Define a Visit Schedule', '', 'interactive', 8,
'{"type":"order-steps","instruction":"Put these clinical trial visits in the correct chronological order:","data":{"steps":[{"id":"w12","text":"Week 12 Visit"},{"id":"screen","text":"Screening Visit"},{"id":"eos","text":"End of Study Visit"},{"id":"baseline","text":"Baseline Visit (Day 0)"},{"id":"w4","text":"Week 4 Visit"},{"id":"w8","text":"Week 8 Visit"}],"correctOrder":["screen","baseline","w4","w8","w12","eos"]},"successMessage":"Correct! Screening → Baseline → Week 4 → Week 8 → Week 12 → End of Study."}'),
(3, 'Event-CRF Assignment', '<h2>Assigning Forms to Visits</h2><p>After creating the study and its visits, assign which CRF forms are collected at each visit:</p><ol><li>Navigate to <strong>Event-CRF Assignment</strong> page</li><li>See a matrix: rows = forms, columns = visits</li><li>Check boxes to assign forms to visits</li><li>For each assignment, set: Required (yes/no), Default status, Ordering</li></ol><p><strong>Example Assignment:</strong></p><table><tr><th>Form</th><th>Screening</th><th>Baseline</th><th>Week 4</th><th>Week 12</th><th>EOS</th></tr><tr><td>Demographics</td><td></td><td>✓</td><td></td><td></td><td></td></tr><tr><td>Vital Signs</td><td>✓</td><td>✓</td><td>✓</td><td>✓</td><td>✓</td></tr><tr><td>Lab Results</td><td>✓</td><td>✓</td><td></td><td>✓</td><td>✓</td></tr><tr><td>Adverse Events</td><td></td><td></td><td>✓</td><td>✓</td><td>✓</td></tr><tr><td>Efficacy</td><td></td><td>✓</td><td>✓</td><td>✓</td><td></td></tr></table><p>This matrix determines what form chips appear for each patient visit.</p>', 'text', 9, NULL),
(3, 'Tabs 7-8: Groups and Settings', '<h2>Final Configuration</h2><p><strong>Tab 7 — Groups:</strong></p><ul><li>Define subject groups for stratification</li><li>Groups used in randomization (e.g., by site, by age group)</li><li>Optional: cohorts for interim analysis</li></ul><p><strong>Tab 8 — Settings:</strong></p><ul><li><strong>Default Workflow</strong> — SDV required? DDE required? Signature required?</li><li><strong>Query Routing</strong> — who receives auto-generated queries by default</li><li><strong>Feature Flags</strong> — enable/disable randomization, eConsent, etc.</li><li><strong>Notifications</strong> — email alerts for enrollment, queries, overdue tasks</li><li><strong>Enrollment Cap</strong> — maximum subjects (hard stop when reached)</li></ul><p><strong>After completing all 8 tabs:</strong> Click "Create Study". The study appears in the Studies list and is ready for site activation and patient enrollment.</p>', 'text', 10, NULL),
(3, 'Knowledge Check: Study Creation', '', 'knowledge-check', 11,
'{"sectionTitle":"Study Creation","questions":[{"id":"st-1","question":"How many tabs are in the Study Creation wizard?","type":"multiple-choice","options":["4","6","8","10"],"correctIndex":2,"explanation":"The wizard has 8 tabs: Basic Info, Facilities, Protocol, Eligibility, Design, Visits, Groups, Settings."},{"id":"st-2","question":"Where do you assign which forms are collected at each visit?","type":"multiple-choice","options":["In the form builder","In Event-CRF Assignment page","In the patient record","In the Settings tab"],"correctIndex":1,"explanation":"Event-CRF Assignment is a separate page where you map forms to visits."},{"id":"st-3","question":"Study parameters can be freely changed after patients are enrolled.","type":"true-false","options":["True","False"],"correctIndex":1,"explanation":"Changes after enrollment may require a protocol amendment and re-consent."}]}'),
(3, 'Exercise: Event-CRF Assignment', '', 'interactive', 12,
'{"type":"match-pairs","instruction":"Match each form to the visits where it is typically collected:","data":{"pairs":[{"left":"Demographics Form","right":"Baseline Visit only (collected once)"},{"left":"Vital Signs Form","right":"Every visit (screening through end of study)"},{"left":"Adverse Event Form","right":"All treatment visits (not screening)"},{"left":"Lab Results Form","right":"Screening, Baseline, and key milestone visits"}]},"successMessage":"Correct! Demographics once at baseline, vital signs at every visit, AE during treatment, labs at key timepoints."}');

-- STUDY-MGMT quiz questions
INSERT INTO acc_training_questions (course_id, question_text, question_type, options, explanation, order_index) VALUES
(3, 'How many tabs does the Study Creation wizard have?', 'multiple_choice', '[{"text":"4","isCorrect":false},{"text":"6","isCorrect":false},{"text":"8","isCorrect":true},{"text":"12","isCorrect":false}]', '8 tabs: Basic Info, Facilities, Protocol, Eligibility, Design, Visits, Groups, Settings.', 1),
(3, 'Which tab defines the scheduled visits and timing windows?', 'multiple_choice', '[{"text":"Tab 2: Facilities","isCorrect":false},{"text":"Tab 5: Design","isCorrect":false},{"text":"Tab 6: Visits","isCorrect":true},{"text":"Tab 8: Settings","isCorrect":false}]', 'Tab 6 (Visits) defines the visit schedule with timing and windows.', 2),
(3, 'Where do you assign CRF forms to specific visits?', 'multiple_choice', '[{"text":"Inside the form builder","isCorrect":false},{"text":"Event-CRF Assignment page","isCorrect":true},{"text":"In each patient record manually","isCorrect":false},{"text":"Tab 6 of the wizard","isCorrect":false}]', 'Event-CRF Assignment is a separate matrix page for form-to-visit mapping.', 3),
(3, 'A visit window of Day 28 ± 3 means the visit can occur on which days?', 'multiple_choice', '[{"text":"Day 25 to Day 31","isCorrect":true},{"text":"Day 28 only","isCorrect":false},{"text":"Day 25 to Day 28","isCorrect":false},{"text":"Day 28 to Day 31","isCorrect":false}]', '± 3 days means 28-3=25 through 28+3=31.', 4),
(3, 'Only Administrators and Data Managers can create studies.', 'true_false', '[{"text":"True","isCorrect":true},{"text":"False","isCorrect":false}]', 'Study creation is restricted to admin and data manager roles.', 5),
(3, 'What does the enrollment cap do?', 'multiple_choice', '[{"text":"Sends a warning email only","isCorrect":false},{"text":"Hard stops enrollment when max subjects reached","isCorrect":true},{"text":"Nothing — it is informational","isCorrect":false},{"text":"Automatically closes all sites","isCorrect":false}]', 'Enrollment cap is a hard stop preventing further patient enrollment.', 6),
(3, 'Study settings can configure default workflow requirements for all forms.', 'true_false', '[{"text":"True","isCorrect":true},{"text":"False","isCorrect":false}]', 'Tab 8 Settings sets default SDV, DDE, signature, and query routing for all forms.', 7),
(3, 'A randomization ratio of 2:1 means:', 'multiple_choice', '[{"text":"2 patients total in the study","isCorrect":false},{"text":"2 patients get treatment for every 1 who gets placebo","isCorrect":true},{"text":"Each site gets 2 patients","isCorrect":false},{"text":"2 visits per patient","isCorrect":false}]', '2:1 means twice as many patients in the active arm vs control.', 8);

-- ============================================================
-- QUERY-MGMT: Add more hands-on exercises
-- ============================================================
INSERT INTO acc_training_slides (course_id, title, content, slide_type, order_index, interactive_config) VALUES
(8, 'Exercise: Respond to a Query (Hands-On)', '', 'interactive', 19,
'{"type":"fill-form","instruction":"A monitor raised a query: ''Weight recorded as 750 kg. Please verify and correct.'' The source document shows the patient weighs 75 kg. Respond to the query:","data":{"fields":[{"label":"Your Response","type":"text","correctAnswer":"any","placeholder":"Explain what happened (e.g., transcription error, extra zero)...","hint":"Reference the source document and explain the discrepancy"},{"label":"Proposed Corrected Value (kg)","type":"number","correctAnswer":"75","placeholder":"Enter the correct weight"},{"label":"Source Document Reference","type":"text","correctAnswer":"any","placeholder":"e.g., Patient chart page 12, vital signs entry dated 2026-04-15"}]},"successMessage":"Correct! You identified the transcription error and proposed the correct value of 75 kg.","hintMessage":"The source shows 75 kg. The entry of 750 was a typo (extra zero)."}'),
(8, 'Exercise: Create a Query (Hands-On)', '', 'interactive', 20,
'{"type":"fill-form","instruction":"You are monitoring a patient record and notice Heart Rate = 30 bpm which seems very low. Create a query on this field:","data":{"fields":[{"label":"Query Subject","type":"text","correctAnswer":"any","placeholder":"e.g., Heart Rate value appears unusually low"},{"label":"Severity","type":"dropdown","options":["Critical","Major","Minor"],"correctAnswer":"Major","hint":"30 bpm is very low but not impossible (athletic bradycardia)"},{"label":"Description","type":"text","correctAnswer":"any","placeholder":"Describe the concern and what you need the site to verify..."},{"label":"Assign To","type":"dropdown","options":["Site Coordinator","Investigator","Data Manager"],"correctAnswer":"Site Coordinator","hint":"Site staff should verify against source documents"}]},"successMessage":"Query created! The site coordinator will verify against source documents and respond.","hintMessage":"Severity should be Major (unusual but possible). Assign to Site Coordinator who can check source docs."}');

-- PATIENT-MGMT: Add more detail
INSERT INTO acc_training_slides (course_id, title, content, slide_type, order_index, interactive_config) VALUES
(6, 'Patient Detail: Editing and Managing', '<h2>Working with Patient Records</h2><p><strong>The Patient Detail View shows:</strong></p><ul><li><strong>Header:</strong> Subject ID, status badge, enrollment date, assigned site, study arm</li><li><strong>Visit Timeline:</strong> Horizontal row of visit columns (Screening, Baseline, Week 4...)</li><li><strong>Form Chips:</strong> Colored chips within each visit column representing assigned CRFs</li><li><strong>Progress Bar:</strong> Overall form completion percentage</li></ul><p><strong>Form Chip Actions (click a chip):</strong></p><ul><li>Gray chip → Opens blank form for data entry</li><li>Blue chip → Opens in-progress form to continue entry</li><li>Green chip → Opens completed form for review</li><li>Purple chip → Opens signed form (read-only unless unlock requested)</li></ul><p><strong>Patient Actions (header buttons):</strong></p><ul><li><strong>Add Unscheduled Visit</strong> — for adverse events, early termination</li><li><strong>Transfer Patient</strong> — move to different site</li><li><strong>Withdraw Patient</strong> — mark as withdrawn (preserves all data)</li><li><strong>View Audit Trail</strong> — see all changes to this patient''s data</li></ul>', 'text', 16, NULL),
(6, 'Exercise: Navigate a Patient Record', '', 'interactive', 17,
'{"type":"scenario","instruction":"A patient (SUBJ-042) needs their Week 4 Vital Signs form completed. How do you get there?","data":{"context":"You are logged in as a Coordinator. You need to enter vital signs data for patient SUBJ-042 at their Week 4 visit.","choices":[{"text":"Go to Forms page → find Vital Signs → enter data","correct":false,"feedback":"The Forms page manages form TEMPLATES, not patient data. You need to go through the Patients page."},{"text":"Go to Patients → search SUBJ-042 → click patient → find Week 4 column → click Vital Signs chip","correct":true,"feedback":"Correct! Always navigate through Patients → specific patient → visit column → form chip to enter data."},{"text":"Go to Studies → select the study → enter data","correct":false,"feedback":"Studies page manages study configuration, not individual patient data entry."},{"text":"Go to My Tasks and wait for it to appear","correct":false,"feedback":"My Tasks shows assigned work but the form might not be a task yet. Direct navigation is: Patients → Patient → Visit → Form."}]},"successMessage":"Navigate through: Patients → Search → Patient Detail → Visit Column → Form Chip!"}');

COMMIT;
