-- Delete existing VAL-RULES slides and replace with comprehensive content
DELETE FROM acc_training_slides WHERE course_id = 7;
DELETE FROM acc_training_questions WHERE course_id = 7;

-- VAL-RULES comprehensive slides (course_id = 7)
INSERT INTO acc_training_slides (course_id, title, content, slide_type, order_index) VALUES
(7, 'Why Validation Rules Matter', '<h2>Data Quality at the Point of Entry</h2><p>Validation rules automatically check data as users enter it — catching errors before they reach the database.</p><ul><li>Prevent impossible values (negative age, future dates)</li><li>Flag unusual values for human review (HR of 200 bpm)</li><li>Enforce required field combinations</li><li>Reduce query volume by catching typos immediately</li><li>Required by 21 CFR Part 11 §11.10(h)</li></ul><p><strong>Key concept:</strong> Rules are set at the <em>form template</em> level. One rule applies to ALL instances of that form across all subjects and visits.</p>', 'text', 1),
(7, 'Navigating to Validation Rules', '<h2>Getting There</h2><ol><li>Click <strong>Validation Rules</strong> in the sidebar</li><li>Select a form from the dropdown (shows rule count per form)</li><li>All fields appear as expandable cards</li></ol><p><strong>Actions Toolbar:</strong></p><ul><li><strong>Quick Add</strong> (lightning bolt) — preset templates</li><li><strong>Custom Rule</strong> (wrench) — full rule builder wizard</li><li><strong>Regex & Formula Reference</strong> (book) — syntax help</li><li><strong>Refresh</strong> — reload from server</li></ul><p><strong>Per-field cards show:</strong> field name, type badge, rule count, AI button, expand/collapse.</p><p>Expand a card to see all rules, test panel, and add/edit/delete buttons.</p>', 'text', 2),
(7, 'Quick Add: 28 Preset Templates', '<h2>Fastest Way to Add Common Rules</h2><p>Click the <strong>Quick Add</strong> button. Templates in 5 categories:</p><table><tr><th>Category</th><th>Templates</th></tr><tr><td><strong>Number Ranges</strong></td><td>Age 18-120, Age 0-17 (pediatric), Weight 1-300 kg, Height 30-250 cm, BMI 10-60, Custom range</td></tr><tr><td><strong>Vital Signs</strong></td><td>Systolic BP 60-250, Diastolic BP 40-150, Heart Rate 30-220, Temp 35-42°C, SpO2 50-100%, Resp Rate 5-60</td></tr><tr><td><strong>Lab Values</strong></td><td>Hemoglobin 5-20, WBC 1K-30K, Platelets 50K-600K, Creatinine 0.1-15, ALT 0-300, Glucose 30-500</td></tr><tr><td><strong>Text Format</strong></td><td>Email, US phone, Letters only, Numbers only, Subject ID (SITE-001), No special chars</td></tr><tr><td><strong>Comparisons</strong></td><td>A > B, A = B, A before B (dates), A ≠ B</td></tr></table><p>Click a template → pick the target field → click Create. Done in seconds.</p>', 'text', 3),
(7, 'Exercise: Add a Quick Rule', '', 'interactive', 4),
(7, 'The Custom Rule Builder: 6-Step Wizard', '<h2>Building Rules From Scratch</h2><p>Click <strong>Custom Rule</strong> to open the wizard:</p><ol><li><strong>Step 1: Which Field?</strong> — Select from dropdown (grouped by section)</li><li><strong>Step 1.5: Table Cell Targeting</strong> — If table field: choose column + row scope</li><li><strong>Step 2: What Check?</strong> — The mega-dropdown with 30+ check types</li><li><strong>Step 3: Configure</strong> — Set values, ranges, patterns (varies by check type)</li><li><strong>Step 4: Severity</strong> — Block Save (red) vs Create Query (amber)</li><li><strong>Step 5: Name & Message</strong> — Rule name + error message text</li><li><strong>Step 6: Create</strong> — Saves and activates immediately</li></ol><p><strong>Important:</strong> Rule creation requires e-signature per 21 CFR Part 11.</p>', 'text', 5),
(7, 'The Mega-Dropdown: All Check Types', '<h2>30+ Check Types in 11 Groups</h2><table><tr><th>Group</th><th>Check Types</th></tr><tr><td>Required</td><td>Field must be filled in</td></tr><tr><td>Number Range</td><td>Between min and max</td></tr><tr><td>Text Format</td><td>Letters only, Numbers only, Alphanumeric, No special chars, Email, US phone, Intl phone</td></tr><tr><td>Date/Time</td><td>MM/DD/YYYY, DD/MM/YYYY, ISO date, ISO datetime, 24hr time, 12hr time</td></tr><tr><td>Date Boundary</td><td>Before date, After date, On/before, On/after, Equals date</td></tr><tr><td>Number Format</td><td>Positive, Whole number, Exactly 2 decimals</td></tr><tr><td>ID/Code</td><td>Subject ID pattern, Initials (2-3 uppercase), ZIP code</td></tr><tr><td>Compare Fields</td><td>Greater than, Less than, Equal, Not equal, ≥, ≤ another field</td></tr><tr><td>Compare Value</td><td>>, <, =, ≠, ≥, ≤ a fixed value</td></tr><tr><td>Selection Triggers</td><td>Matches specific option, Matches pattern</td></tr><tr><td>Yes/No Triggers</td><td>When Yes, When No</td></tr><tr><td>Advanced</td><td>Custom regex, Excel-style formula</td></tr></table>', 'text', 6),
(7, 'Knowledge Check: Rule Types', '', 'knowledge-check', 7),
(7, 'Block Save vs Create Query', '<h2>Choosing the Right Severity</h2><table><tr><th>Severity</th><th>What Happens</th><th>When to Use</th><th>Example</th></tr><tr><td><strong>Block Save</strong> (Red)</td><td>User CANNOT submit until fixed</td><td>Physically impossible values</td><td>Negative age, date in year 3000, temperature 0°C</td></tr><tr><td><strong>Create Query</strong> (Amber)</td><td>Saves but auto-creates a query for review</td><td>Unusual but medically possible</td><td>HR=195 (possible during exercise), SBP=210 (hypertensive crisis)</td></tr></table><p><strong>Auto-Query Pipeline:</strong></p><ol><li>User enters unusual value → saves form</li><li>System creates query automatically</li><li>Query assigned per workflow routing config</li><li>Assigned reviewer investigates</li><li>No duplicate queries if one already exists for same field+rule</li></ol>', 'text', 8),
(7, 'Exercise: Choose the Right Severity', '', 'interactive', 9),
(7, 'AI Rule Suggester', '<h2>Intelligent Recommendations</h2><p>Each field card has an <strong>AI</strong> button (sparkle icon). Click it to get smart suggestions:</p><ul><li>Analyzes field name, type, and context</li><li>Considers other fields in the form for cross-field rules</li><li>Generates suggestions with confidence scores</li><li>Pre-fills rule name, check type, ranges, and error message</li><li>Accept, modify, or reject each suggestion</li></ul><p><strong>When to use:</strong> Setting up a new form and want a quick starting point. AI is especially good at suggesting range checks for clinical values and cross-field comparisons.</p><p><strong>Example:</strong> For a "Systolic BP" field, AI suggests range 60-250, severity "Create Query", message "Systolic BP outside expected range."</p>', 'text', 10),
(7, 'Table Cell Targeting', '<h2>Rules on Specific Table Cells</h2><p>For Data Table and Question Table fields, you can target rules precisely:</p><ul><li><strong>Entire table</strong> — rule checks all cells</li><li><strong>Specific column</strong> — select column, then:<ul><li><strong>All rows</strong> — checks every row in that column</li><li><strong>Specific row</strong> — targets one exact cell</li></ul></li></ul><p><strong>Example:</strong> In a Lab Results table with columns [Test Name, Value, Units, Normal Range]:<br>Rule: "Column 2 (Value) must be a positive number" → applies to all rows in the Value column.</p><p><strong>Cross-column comparison:</strong> "Column 2 (Value) must be less than Column 4 (Upper Normal)" — validates each row independently.</p>', 'text', 11),
(7, 'Testing and Managing Rules', '<h2>Verify Before Activating</h2><p><strong>Inline Testing:</strong></p><ul><li>Expand a field card → "Test This Question" panel</li><li>Enter boundary values to verify pass/fail</li><li>Test values: min-1, min, mid, max, max+1</li></ul><p><strong>Managing Existing Rules:</strong></p><ul><li><strong>Enable/Disable</strong> — toggle On/Off without deleting</li><li><strong>Edit</strong> — modify range, message, or severity</li><li><strong>Delete</strong> — permanently remove (e-signature required)</li><li><strong>Refresh</strong> — reload rules from server</li></ul><p><strong>Best Practices:</strong></p><ul><li>Test with boundary values before activating</li><li>Start with "Create Query" severity, upgrade to "Block Save" after confirming no false positives</li><li>Use descriptive rule names for audit trail clarity</li><li>Document the clinical rationale in the Description field</li></ul>', 'text', 12),
(7, 'Regex and Formula Reference', '<h2>Advanced Rule Configuration</h2><p>Click the <strong>Regex & Formula Reference</strong> button (book icon) for a 3-tab popup:</p><p><strong>Tab 1: Regex Syntax</strong></p><ul><li><code>^</code> start, <code>$</code> end, <code>.</code> any char, <code>*</code> zero+, <code>+</code> one+</li><li><code>[A-Z]</code> uppercase, <code>[0-9]</code> digit, <code>\d</code> digit shorthand</li><li><code>{n}</code> exactly n times, <code>{n,m}</code> n to m times</li></ul><p><strong>Tab 2: Preset Patterns</strong></p><ul><li>Email: <code>^[\\w.-]+@[\\w.-]+\\.[a-z]{2,}$</code></li><li>Phone: <code>^\\(?\\d{3}\\)?[-\\s]?\\d{3}[-\\s]?\\d{4}$</code></li><li>Subject ID: <code>^[A-Z]{2,4}-\\d{3,4}$</code></li></ul><p><strong>Tab 3: Formula Functions</strong></p><ul><li><code>=AND(cond1, cond2)</code> — all must be true</li><li><code>=OR(cond1, cond2)</code> — any can be true</li><li><code>=IF(condition, true_val, false_val)</code></li><li>Reference fields: <code>{fieldName}</code> syntax</li></ul>', 'text', 13),
(7, 'Exercise: Create a Custom Rule', '', 'interactive', 14),
(7, 'Knowledge Check: Rule Management', '', 'knowledge-check', 15);

-- VAL-RULES exercise configs
UPDATE acc_training_slides SET interactive_config = '{"type":"scenario","instruction":"You need to add a range check for Heart Rate (30-220 bpm) on a Vital Signs form. What is the fastest method?","data":{"context":"You are configuring validation for a new Vital Signs CRF. Heart Rate needs a range check.","choices":[{"text":"Open the Custom Rule Builder wizard and configure from scratch","correct":false,"feedback":"This works but is slower. Quick Add has a pre-built Heart Rate template."},{"text":"Click Quick Add → Vital Signs → Heart Rate 30-220 bpm","correct":true,"feedback":"Correct! Quick Add has preset templates for common vital signs ranges. One click, pick the field, done."},{"text":"Ask the AI Suggester to recommend a rule","correct":false,"feedback":"AI Suggester works but Quick Add is faster for standard vital sign ranges that have exact templates."},{"text":"Write a custom regex pattern","correct":false,"feedback":"Regex is for text format validation, not numeric ranges. Use Quick Add for number ranges."}]},"successMessage":"Quick Add is the fastest path for standard clinical value ranges!"}'
WHERE course_id = 7 AND order_index = 4;

UPDATE acc_training_slides SET interactive_config = '{"type":"scenario","instruction":"A Systolic BP field can realistically range from 60-250 mmHg. Values outside this are unusual but medically possible (shock, hypertensive crisis). Which severity should you choose?","data":{"context":"You are creating a validation rule for Systolic Blood Pressure. Normal range is 90-140, but values 60-250 are medically possible in extreme cases.","choices":[{"text":"Block Save — prevent form submission for any value outside 60-250","correct":false,"feedback":"Block Save prevents data entry of real clinical values. A patient in hypertensive crisis (SBP=260) would be unable to have their data recorded."},{"text":"Create Query — allow save but flag values outside 90-140 for review","correct":true,"feedback":"Correct! Use Create Query for clinically unusual but possible values. This flags them for review without blocking legitimate data entry."},{"text":"No validation needed — any BP value should be accepted","correct":false,"feedback":"No validation means typos like 6000 mmHg would go undetected. Always add range checks for clinical values."},{"text":"Block Save for anything outside 90-140","correct":false,"feedback":"90-140 is normal range, not physiological limits. Blocking save at 141 would prevent recording data for any hypertensive patient."}]},"successMessage":"Create Query is correct for clinically unusual but possible values!"}'
WHERE course_id = 7 AND order_index = 9;

UPDATE acc_training_slides SET interactive_config = '{"type":"order-steps","instruction":"Put the Custom Rule Builder wizard steps in correct order:","data":{"steps":[{"id":"name","text":"Step 5: Set Rule Name and Error Message"},{"id":"field","text":"Step 1: Select the Target Field"},{"id":"severity","text":"Step 4: Choose Severity (Block Save or Create Query)"},{"id":"check","text":"Step 2: Select Check Type from Mega-Dropdown"},{"id":"create","text":"Step 6: Click Create Rule"},{"id":"config","text":"Step 3: Configure Values/Ranges/Patterns"}],"correctOrder":["field","check","config","severity","name","create"]},"successMessage":"Correct! Field → Check Type → Configure → Severity → Name → Create."}'
WHERE course_id = 7 AND order_index = 14;

-- Knowledge check configs for VAL-RULES
UPDATE acc_training_slides SET interactive_config = '{"sectionTitle":"Rule Types and Creation","questions":[{"id":"vr-1","question":"How many preset templates are available in Quick Add?","type":"multiple-choice","options":["10","20","28","50"],"correctIndex":2,"explanation":"Quick Add offers 28 preset templates across 5 categories."},{"id":"vr-2","question":"The mega-dropdown in the Custom Rule Builder has how many check types?","type":"multiple-choice","options":["10","20","30+","100+"],"correctIndex":2,"explanation":"The mega-dropdown offers 30+ check types in 11 groups."},{"id":"vr-3","question":"Rules are configured per-patient.","type":"true-false","options":["True","False"],"correctIndex":1,"explanation":"Rules are configured at the form template level and apply to ALL instances across all subjects."}]}'
WHERE course_id = 7 AND order_index = 7;

UPDATE acc_training_slides SET interactive_config = '{"sectionTitle":"Rule Management","questions":[{"id":"vr-4","question":"What should you test before activating a new rule?","type":"multiple-choice","options":["Only the exact range boundaries","Boundary values: min-1, min, mid, max, max+1","Just one value in the middle","Nothing — rules are always correct"],"correctIndex":1,"explanation":"Test boundary values to ensure the rule fires correctly at edges and passes for valid values."},{"id":"vr-5","question":"Rule changes require an e-signature.","type":"true-false","options":["True","False"],"correctIndex":0,"explanation":"Per 21 CFR Part 11, all validation rule changes require e-signature."},{"id":"vr-6","question":"If a Create Query rule fires but a query already exists for that field, what happens?","type":"multiple-choice","options":["A duplicate query is created","No new query — duplicates are prevented","The existing query is deleted","An error is thrown"],"correctIndex":1,"explanation":"The system prevents duplicate queries for the same field and rule."}]}'
WHERE course_id = 7 AND order_index = 15;

-- VAL-RULES quiz questions (15 questions)
INSERT INTO acc_training_questions (course_id, question_text, question_type, options, explanation, order_index) VALUES
(7, 'Where are validation rules configured?', 'multiple_choice', '[{"text":"Per patient record","isCorrect":false},{"text":"At the form template level (applies to all instances)","isCorrect":true},{"text":"Per study site","isCorrect":false},{"text":"In the database directly","isCorrect":false}]', 'Rules are set on form templates and apply universally.', 1),
(7, 'What is the fastest way to add a Heart Rate range check?', 'multiple_choice', '[{"text":"Custom Rule Builder","isCorrect":false},{"text":"AI Suggester","isCorrect":false},{"text":"Quick Add → Vital Signs template","isCorrect":true},{"text":"Write a formula","isCorrect":false}]', 'Quick Add has a pre-built Heart Rate 30-220 bpm template.', 2),
(7, 'Block Save severity means the user cannot submit until the value is corrected.', 'true_false', '[{"text":"True","isCorrect":true},{"text":"False","isCorrect":false}]', 'Block Save prevents form submission until the error is fixed.', 3),
(7, 'Create Query severity allows save but automatically creates a query for review.', 'true_false', '[{"text":"True","isCorrect":true},{"text":"False","isCorrect":false}]', 'Create Query flags unusual values without blocking data entry.', 4),
(7, 'A patient has SBP of 195. Your rule range is 60-250 with Create Query severity. What happens?', 'multiple_choice', '[{"text":"Form is blocked from saving","isCorrect":false},{"text":"Value is accepted but no query (195 is within 60-250)","isCorrect":true},{"text":"A query is created","isCorrect":false},{"text":"The system crashes","isCorrect":false}]', '195 is within 60-250, so the rule passes. No query is generated.', 5),
(7, 'How many check type groups are in the mega-dropdown?', 'multiple_choice', '[{"text":"5","isCorrect":false},{"text":"8","isCorrect":false},{"text":"11","isCorrect":true},{"text":"20","isCorrect":false}]', 'The mega-dropdown has 11 groups with 30+ total check types.', 6),
(7, 'Table Cell Targeting allows rules on specific columns and rows.', 'true_false', '[{"text":"True","isCorrect":true},{"text":"False","isCorrect":false}]', 'You can target entire table, specific column, or specific cell.', 7),
(7, 'The AI Suggester analyzes field context to suggest appropriate rules.', 'true_false', '[{"text":"True","isCorrect":true},{"text":"False","isCorrect":false}]', 'AI examines field name, type, and context for intelligent suggestions.', 8),
(7, 'You enter BMI = -5 and the rule is "BMI 10-60, Block Save". What happens?', 'multiple_choice', '[{"text":"Form saves with a warning","isCorrect":false},{"text":"A query is created","isCorrect":false},{"text":"Form cannot be submitted until BMI is corrected","isCorrect":true},{"text":"Nothing happens","isCorrect":false}]', 'Block Save prevents submission. User must fix the value.', 9),
(7, 'Which Quick Add category has templates for Hemoglobin and Creatinine?', 'multiple_choice', '[{"text":"Number Ranges","isCorrect":false},{"text":"Vital Signs","isCorrect":false},{"text":"Lab Values","isCorrect":true},{"text":"Comparisons","isCorrect":false}]', 'Lab Values category includes hemoglobin, WBC, platelets, creatinine, ALT, glucose.', 10),
(7, 'Custom regex patterns are used for what type of validation?', 'multiple_choice', '[{"text":"Numeric ranges","isCorrect":false},{"text":"Text format patterns (email, phone, ID)","isCorrect":true},{"text":"Date comparisons","isCorrect":false},{"text":"Cross-field calculations","isCorrect":false}]', 'Regex validates text format patterns, not numeric ranges or dates.', 11),
(7, 'Rules can be disabled without deleting them.', 'true_false', '[{"text":"True","isCorrect":true},{"text":"False","isCorrect":false}]', 'Toggle On/Off to disable without losing the rule configuration.', 12),
(7, 'What formula syntax references other fields?', 'multiple_choice', '[{"text":"[fieldName]","isCorrect":false},{"text":"{fieldName}","isCorrect":true},{"text":"$fieldName","isCorrect":false},{"text":"@fieldName","isCorrect":false}]', 'Use {fieldName} syntax in formulas to reference other fields.', 13),
(7, 'When should you use Block Save vs Create Query for temperature = 45°C?', 'multiple_choice', '[{"text":"Block Save — 45°C is incompatible with life","isCorrect":true},{"text":"Create Query — it might be a real measurement","isCorrect":false},{"text":"No rule needed","isCorrect":false},{"text":"Either is fine","isCorrect":false}]', '45°C is lethal hyperthermia. Block Save is appropriate for impossible values.', 14),
(7, 'What is the correct testing approach before activating a rule?', 'multiple_choice', '[{"text":"Test only the midpoint value","isCorrect":false},{"text":"Test boundary values: min-1, min, mid, max, max+1","isCorrect":true},{"text":"No testing needed","isCorrect":false},{"text":"Only test one failing value","isCorrect":false}]', 'Boundary testing ensures the rule fires correctly at edges.', 15);
