-- ============================================================================
-- SLIDES: DATA-ENTRY (SOP-029)
-- ============================================================================
INSERT INTO acc_training_slides (course_id, title, content, slide_type, order_index)
SELECT c.id, s.title, s.content, 'text', s.idx
FROM acc_training_courses c
CROSS JOIN (VALUES
(1, 'Welcome to Clinical Data Entry', '<h2>Clinical Data Entry Training</h2><p>This module teaches you how to enter clinical trial data into AccuraTrial EDC accurately and compliantly.</p><p><strong>What you will learn:</strong></p><ul><li>Navigate to patient forms</li><li>Understand form statuses and field types</li><li>Enter data and handle validation errors</li><li>Submit forms with electronic signatures</li><li>Make corrections with reason-for-change</li></ul><div class="tip"><strong>Regulatory:</strong> All data entry is governed by 21 CFR Part 11 §11.10(e) and ICH E6(R2) GCP §8.3.13.</div>'),
(2, 'Understanding CRF Forms', '<h2>What Is a CRF?</h2><p>A <strong>Case Report Form (CRF)</strong> is an electronic form used to collect clinical trial data for each patient visit.</p><p><strong>Form Status Lifecycle:</strong></p><ol><li><strong>Not Started</strong> (gray) — form exists but no data entered</li><li><strong>In Progress</strong> (blue) — data entry has begun</li><li><strong>Complete</strong> (green) — all required fields filled</li><li><strong>Signed</strong> (purple) — e-signature applied</li><li><strong>Frozen</strong> (light blue) — no changes without unfreezing</li><li><strong>Locked</strong> (red) — permanently locked for database lock</li></ol>'),
(3, 'Navigating to Patient Forms', '<h2>Finding the Right Form</h2><p>The data entry workflow follows this path:</p><ol><li><strong>Go to Patients page</strong> — click "Patients" in the sidebar</li><li><strong>Select a patient</strong> — click the patient row to open their record</li><li><strong>Find the visit</strong> — scheduled visits appear as columns</li><li><strong>Click the form chip</strong> — colored chips represent forms within each visit</li></ol><p>The form chip color indicates its status. Click any chip to open the form for data entry.</p><div class="step-action"><strong>Try it:</strong> Navigate to a patient and click a form chip to open it.</div>'),
(4, 'The Data Entry Interface', '<h2>What You See When a Form Opens</h2><p>The form modal has three sections:</p><ul><li><strong>Header Bar</strong> — form name, version, status badge, patient ID, visit name</li><li><strong>Form Body</strong> — fields organized in sections with labels, inputs, and validation indicators</li><li><strong>Footer</strong> — action buttons: Save Draft, Submit and Sign, Close</li></ul><p>Fields may be organized in single or multi-column layouts depending on form design.</p>'),
(5, 'Field Types and Data Entry', '<h2>Entering Data Into Fields</h2><p>AccuraTrial supports 15+ field types. Common ones:</p><table><tr><th>Field Type</th><th>How to Enter</th></tr><tr><td>Text</td><td>Type directly into the field</td></tr><tr><td>Number</td><td>Type numbers only — decimal allowed if configured</td></tr><tr><td>Date</td><td>Use the date picker or type in ISO format (YYYY-MM-DD)</td></tr><tr><td>Dropdown</td><td>Click to open options, select one</td></tr><tr><td>Radio Buttons</td><td>Click one option from the group</td></tr><tr><td>Checkbox</td><td>Check one or more options</td></tr><tr><td>Textarea</td><td>Type longer text entries (comments, narratives)</td></tr></table><p><strong>Skip Logic:</strong> Some fields appear/disappear based on your answers in other fields.</p>'),
(6, 'Handling Validation Errors', '<h2>Validation During Data Entry</h2><p>As you enter data, validation rules check your entries in real time:</p><p><strong>Red Error (Blocks Save):</strong></p><ul><li>Prevents form submission until corrected</li><li>Example: Age cannot be negative, required field empty</li><li>Fix the value to clear the error</li></ul><p><strong>Yellow Warning (Creates Query):</strong></p><ul><li>Allows save but automatically generates a data query</li><li>Example: Heart rate of 200 — unusual but possible</li><li>You may proceed, but must respond to the query later</li></ul><div class="step-action"><strong>Try it:</strong> Enter an invalid value in a field and observe the validation feedback.</div>'),
(7, 'Query Indicators on Forms', '<h2>Queries Attached to Fields</h2><p>You may see query indicators (speech bubble icons) next to fields. These mean:</p><ul><li><strong>Orange bubble</strong> — open query requiring your response</li><li><strong>Green bubble</strong> — resolved query (for reference)</li><li><strong>Red bubble</strong> — critical query from validation failure</li></ul><p>Click the indicator to view the query details, add a response, or propose a correction.</p>'),
(8, 'Submitting and Signing', '<h2>Completing a Form</h2><p>When all required fields are filled and validation errors are resolved:</p><ol><li><strong>Review your entries</strong> — scroll through the form to verify accuracy</li><li><strong>Click "Submit and Sign"</strong> — this initiates the e-signature process</li><li><strong>Electronic Signature</strong> — enter your username, password, and reason for signing</li><li><strong>Confirmation</strong> — form status changes to "Signed"</li></ol><div class="warning"><strong>21 CFR Part 11:</strong> Your e-signature is legally binding and equivalent to a handwritten signature. The system records who signed, when, and why.</div>'),
(9, 'Making Corrections (Reason for Change)', '<h2>Editing After Submission</h2><p>If you need to correct data after submission, you must provide a <strong>Reason for Change</strong>:</p><ol><li>Open the signed form</li><li>Click the field you need to change</li><li>Enter the new value</li><li>A popup asks: "Why are you making this change?"</li><li>Type your reason and confirm</li></ol><p><strong>What Gets Recorded in the Audit Trail:</strong></p><ul><li>Original value (preserved forever)</li><li>New value</li><li>Who made the change</li><li>When (timestamp)</li><li>Why (your reason)</li></ul><p>The original e-signature is invalidated — a new signature is required.</p>'),
(10, 'Locked and Frozen Forms', '<h2>Understanding Form States</h2><p><strong>Frozen Forms:</strong></p><ul><li>Temporarily locked — no edits allowed</li><li>Can be unfrozen by a data manager if corrections are needed</li><li>Used during data review periods</li></ul><p><strong>Locked Forms:</strong></p><ul><li>Permanently locked for database lock</li><li>Cannot be edited under any circumstances</li><li>Represents final, submission-ready data</li></ul><p>If you need to edit a locked form, contact your data manager to discuss the unlock request process.</p>'),
(11, 'Best Practices for Data Entry', '<h2>Data Entry Best Practices</h2><p><strong>Before You Start:</strong></p><ul><li>Have source documents ready</li><li>Verify you are entering data for the correct patient and visit</li><li>Check that the form version matches your protocol</li></ul><p><strong>While Entering Data:</strong></p><ul><li>Enter data contemporaneously (at or near the time of collection)</li><li>Use the Save Draft button frequently</li><li>Address validation errors immediately</li><li>Do not leave required fields blank</li></ul><p><strong>After Entering Data:</strong></p><ul><li>Review all entries before submitting</li><li>Apply your e-signature promptly</li><li>Respond to any auto-generated queries within 48 hours</li></ul>'),
(12, 'Module Summary', '<h2>Key Takeaways</h2><ul><li>Navigate: Patients → Select Patient → Visit → Form Chip</li><li>Form statuses progress: Not Started → In Progress → Complete → Signed → Frozen → Locked</li><li>Red errors block save; yellow warnings create queries but allow save</li><li>Submit and Sign applies a legally-binding e-signature</li><li>Corrections require Reason for Change — audit trail preserves the original</li><li>Save frequently — use Save Draft before Submit and Sign</li><li>Frozen forms can be unfrozen; locked forms cannot be edited</li></ul><p><strong>Ready for the quiz!</strong></p>')
) AS s(idx, title, content)
WHERE c.course_code = 'DATA-ENTRY'
AND NOT EXISTS (SELECT 1 FROM acc_training_slides WHERE course_id = c.id);
