-- ============================================================================
-- SLIDES: LOGIN-NAV (SOP-032)
-- ============================================================================
INSERT INTO acc_training_slides (course_id, title, content, slide_type, order_index)
SELECT c.id, s.title, s.content, 'text', s.idx
FROM acc_training_courses c
CROSS JOIN (VALUES
(1, 'Welcome to AccuraTrial EDC', '<h2>Login and Navigation Training</h2><p>Welcome to AccuraTrial EDC. This module teaches you how to sign in and navigate the system effectively.</p><p><strong>What you will learn:</strong></p><ul><li>How to sign in with username/password or Google</li><li>Navigate the dashboard and sidebar</li><li>Find tasks, patients, forms, and reports</li><li>Manage your profile and sign out safely</li></ul><div class="tip"><strong>Regulatory Note:</strong> AccuraTrial is 21 CFR Part 11 compliant. Always sign out when finished.</div>'),
(2, 'Before You Start — Prerequisites', '<h2>What You Need</h2><table><tr><th>Requirement</th><th>Where to Get It</th></tr><tr><td>Username</td><td>Provided by your system administrator</td></tr><tr><td>Temporary Password</td><td>Given at account creation — change on first login</td></tr><tr><td>Web Browser</td><td>Chrome, Edge, or Firefox (latest version)</td></tr><tr><td>Internet Connection</td><td>Stable connection required</td></tr></table><div class="tip"><strong>Tip:</strong> Bookmark the login URL for quick daily access.</div>'),
(3, 'Step 1: Open the Login Page', '<h2>Opening AccuraTrial</h2><p>Open your web browser and navigate to the URL provided by your administrator (e.g., <code>https://accuratrials.com</code>).</p><p>You will see the login screen with two compliance badges:</p><ul><li><strong>HIPAA Compliant</strong> — patient data protection</li><li><strong>21 CFR Part 11</strong> — electronic records standard</li></ul><div class="step-action"><strong>Try it:</strong> Open the AccuraTrial login page in your browser now.</div>'),
(4, 'Step 2: Enter Your Credentials', '<h2>Signing In</h2><p>Enter your <strong>username</strong> in the first field and your <strong>password</strong> in the second field.</p><p><strong>Password Rules:</strong></p><ul><li>Minimum 8 characters</li><li>Mix of uppercase, lowercase, numbers, and symbols</li><li>Expires every 90 days</li><li>5 failed attempts = 15-minute lockout (21 CFR Part 11 §11.300(d))</li></ul><div class="step-action"><strong>Try it:</strong> Enter your username and password, then click "Sign In".</div>'),
(5, 'The Dashboard — Your Home Screen', '<h2>Welcome to Your Dashboard</h2><p>After signing in, you land on the <strong>Dashboard</strong> — your command center.</p><p><strong>What you will see:</strong></p><ul><li><strong>Top Navigation Bar</strong> — notifications, profile, sign-out</li><li><strong>Statistics Cards</strong> — enrollment, forms, queries at a glance</li><li><strong>Recent Activity</strong> — latest actions in your studies</li><li><strong>My Tasks</strong> — items requiring your attention</li></ul><p>The dashboard content varies by your role — administrators see everything, while coordinators see their assigned patients.</p>'),
(6, 'The Sidebar Navigation', '<h2>Getting Around with the Sidebar</h2><p>The left sidebar is your primary navigation tool. It is organized into sections:</p><p><strong>Main Section:</strong></p><ul><li>Dashboard — return home</li><li>My Tasks — your action items</li><li>Queries — data queries assigned to you</li></ul><p><strong>Clinical Section:</strong></p><ul><li>Patients — patient/subject list</li><li>Forms — CRF template management</li><li>Studies — study configuration</li></ul><p><strong>Admin Section (administrators only):</strong></p><ul><li>Users — manage accounts</li><li>Reports — analytics dashboards</li><li>Settings — system configuration</li></ul><div class="tip"><strong>Tip:</strong> Click the collapse icon to minimize the sidebar for more screen space.</div>'),
(7, 'Navigating Between Pages', '<h2>Moving Through the System</h2><p>Click any sidebar item to navigate to that page. Key destinations:</p><ul><li><strong>My Tasks</strong> — see forms to complete, queries to answer, signatures needed</li><li><strong>Queries</strong> — view and respond to data queries</li><li><strong>Patients</strong> — access patient records and enter data</li><li><strong>Forms</strong> — design and manage CRF templates</li><li><strong>Studies</strong> — configure study parameters and visits</li><li><strong>Reports</strong> — view enrollment, data quality, and custom reports</li></ul><div class="step-action"><strong>Try it:</strong> Click through each sidebar item to familiarize yourself with the pages.</div>'),
(8, 'Your Profile and Signing Out', '<h2>Managing Your Session</h2><p><strong>Viewing Your Profile:</strong> Click your name/avatar in the top-right corner to see your profile details, role, and permissions.</p><p><strong>Signing Out:</strong> Always use the "Sign Out" button — never just close the browser tab.</p><div class="warning"><strong>Important:</strong> For audit compliance, always sign out properly. The system logs your session duration.</div><p><strong>Session Timeout:</strong> If inactive for 30 minutes, you will be automatically signed out (21 CFR Part 11 requirement). A warning appears at 25 minutes.</p>'),
(9, 'What You See Depends on Your Role', '<h2>Role-Based Access</h2><table><tr><th>Role</th><th>Access Level</th></tr><tr><td>Administrator</td><td>Full system access — all menus visible</td></tr><tr><td>Data Manager</td><td>Patients, Tasks, Queries, Forms, Studies, Validation, Data Locks, Reports</td></tr><tr><td>Investigator</td><td>Patients, Tasks, Queries, Randomization, SDV</td></tr><tr><td>Coordinator (CRC)</td><td>Patients, Tasks, Queries, Forms, Studies, Sites</td></tr><tr><td>Monitor</td><td>Patients, Tasks, Queries, SDV, Audit Logs, Reports</td></tr><tr><td>Viewer (Sponsor)</td><td>Patients, Reports, Queries (read-only)</td></tr></table><p>If you cannot see a menu item, your role may not have access. Contact your administrator.</p>'),
(10, 'Tips for Getting Started', '<h2>Quick-Start Tips</h2><ol><li><strong>Check My Tasks first</strong> — this shows everything that needs your attention today</li><li><strong>Use the search function</strong> — quickly find patients, forms, or studies by name/ID</li><li><strong>Watch notification badges</strong> — red badges on sidebar items mean action is needed</li><li><strong>Bookmark the login URL</strong> — save time each day</li><li><strong>Save frequently</strong> — don''t lose work; auto-save is not available on all forms</li></ol><div class="tip"><strong>Remember:</strong> When in doubt, check My Tasks — it aggregates all pending work across the system.</div>'),
(11, 'Troubleshooting Common Issues', '<h2>Common Problems and Solutions</h2><table><tr><th>Problem</th><th>Solution</th></tr><tr><td>Cannot log in</td><td>Check caps lock, verify username spelling, wait 15 min if locked out after 5 failed attempts</td></tr><tr><td>Page will not load</td><td>Check internet connection, try refreshing, clear browser cache, try Chrome/Edge</td></tr><tr><td>Cannot find a menu item</td><td>Your role may not have access — contact your administrator</td></tr><tr><td>System logged me out</td><td>Normal after 30 minutes of inactivity — sign back in and your work is saved</td></tr></table>'),
(12, 'Module Summary', '<h2>Key Takeaways</h2><ul><li>Sign in at the URL provided by your administrator</li><li>The Dashboard is your home screen with key metrics and tasks</li><li>Use the Sidebar to navigate between sections</li><li>Your role determines what menu items you see</li><li>Always sign out properly — never just close the tab</li><li>Check My Tasks daily for pending action items</li><li>Session times out after 30 minutes of inactivity</li></ul><p><strong>You are now ready to take the quiz!</strong> The quiz tests your understanding of login, navigation, and session management.</p>')
) AS s(idx, title, content)
WHERE c.course_code = 'LOGIN-NAV'
AND NOT EXISTS (SELECT 1 FROM acc_training_slides WHERE course_id = c.id);
