-- ============================================================================
-- SLIDES: QUERY-MGMT (SOP-020)
-- ============================================================================
INSERT INTO acc_training_slides (course_id, title, content, slide_type, order_index)
SELECT c.id, s.title, s.content, 'text', s.idx
FROM acc_training_courses c
CROSS JOIN (VALUES
(1, 'Welcome to Query Management', '<h2>Query Management Training</h2><p>Queries are how your team flags, discusses, and resolves data issues in clinical trials.</p><p><strong>What you will learn:</strong></p><ul><li>What queries are and how they are created</li><li>Navigate the Queries dashboard</li><li>Respond to and resolve queries</li><li>Understand automatic query generation</li><li>Use bulk operations</li></ul>'),
(2, 'Understanding Query Types', '<h2>Types of Queries</h2><table><tr><th>Type</th><th>When Used</th></tr><tr><td><strong>Query</strong></td><td>General data question — manually created by monitor or data manager</td></tr><tr><td><strong>Failed Validation</strong></td><td>Auto-created when a validation rule with "Create Query" severity fails</td></tr><tr><td><strong>Annotation</strong></td><td>Informational note — does not require response</td></tr><tr><td><strong>Reason for Change</strong></td><td>Records why a value was modified after entry</td></tr></table><p><strong>Query Severity:</strong> Critical (red), Major (orange), Minor (yellow)</p>'),
(3, 'The Queries Dashboard', '<h2>Navigating to Queries</h2><p>Click <strong>Queries</strong> in the sidebar to open the queries dashboard.</p><p><strong>Dashboard Features:</strong></p><ul><li><strong>Summary cards</strong> — total open, assigned to you, overdue, resolved today</li><li><strong>Filter bar</strong> — filter by status, severity, study, site, assigned user</li><li><strong>Query table</strong> — sortable list with patient, form, field, status, age</li><li><strong>Bulk actions</strong> — select multiple queries for batch operations</li></ul><div class="step-action"><strong>Try it:</strong> Open the Queries page and explore the filter options.</div>'),
(4, 'Creating a Query Manually', '<h2>How to Raise a Query</h2><p>To create a new query on a data field:</p><ol><li>Open the patient''s form</li><li>Click the query icon next to the field in question</li><li>Select "Create Query" from the popup</li><li>Fill in: Subject, Severity, Description, Assigned To</li><li>Click "Create"</li></ol><p>The query is now visible to the assigned user in their My Tasks and on the Queries dashboard.</p><div class="tip"><strong>Best Practice:</strong> Be specific in your description. Reference the source document or protocol section that shows the discrepancy.</div>'),
(5, 'Responding to a Query', '<h2>Answering Queries Assigned to You</h2><p>When a query is assigned to you:</p><ol><li>Find it in My Tasks or the Queries dashboard</li><li>Click to open the Query Details modal</li><li>Review the question and the current field value</li><li>Type your response explaining the data or proposing a correction</li><li>If correcting: enter the new value in the "Proposed Value" field</li><li>Click "Submit Response"</li></ol><p>The query status changes to "Answered" and returns to the originator for review.</p>'),
(6, 'Query Resolution Workflow', '<h2>The Full Query Lifecycle</h2><ol><li><strong>Open</strong> — query created, waiting for response</li><li><strong>Answered</strong> — assignee has responded</li><li><strong>Accepted</strong> — originator accepts the response, query resolved</li><li><strong>Rejected</strong> — originator rejects response, returns to assignee</li><li><strong>Closed</strong> — final state after acceptance + e-signature</li></ol><p><strong>Closing requires an e-signature</strong> — the person closing the query must authenticate with username + password + reason.</p>'),
(7, 'Automatic Query Generation', '<h2>Validation-Generated Queries</h2><p>When a validation rule is configured with "Create a Query" severity:</p><ol><li>User enters data that fails the validation check</li><li>System shows a yellow warning but allows save</li><li>A query is automatically created with:</li></ol><ul><li>Subject: Auto-generated from rule name</li><li>Description: The rule''s custom message</li><li>Severity: As configured in the rule</li><li>Assigned To: Based on workflow routing configuration</li></ul><p>These queries appear immediately in the assignee''s task list.</p>'),
(8, 'Bulk Operations', '<h2>Managing Multiple Queries</h2><p>For large studies with many queries, use bulk operations:</p><ol><li>Select multiple queries using checkboxes</li><li>Choose a bulk action from the toolbar</li></ol><p><strong>Available Bulk Actions:</strong></p><ul><li>Reassign — move queries to a different user</li><li>Change severity — upgrade/downgrade multiple queries</li><li>Export — download query list as CSV/Excel</li><li>Close — batch-close resolved queries (requires e-signature)</li></ul><div class="tip"><strong>Tip:</strong> Use filters first to narrow down the list, then select all visible queries for bulk action.</div>'),
(9, 'Query Indicators on Forms', '<h2>Visual Indicators</h2><p>When viewing a patient form, query indicators appear next to affected fields:</p><ul><li><strong>Orange speech bubble</strong> — open query, needs attention</li><li><strong>Green speech bubble</strong> — resolved/closed query</li><li><strong>Red speech bubble</strong> — critical/overdue query</li><li><strong>Number badge</strong> — multiple queries on same field</li></ul><p>Click any indicator to see the query thread and respond inline without leaving the form.</p>'),
(10, 'Best Practices', '<h2>Query Management Best Practices</h2><ul><li><strong>Respond within 48 hours</strong> — overdue queries delay database lock</li><li><strong>Be specific</strong> — reference source documents in your responses</li><li><strong>Use proposed values</strong> — when correcting data, propose the new value in the query</li><li><strong>Check My Tasks daily</strong> — queries assigned to you appear there</li><li><strong>Don''t ignore warnings</strong> — validation-generated queries still need resolution</li><li><strong>Close promptly</strong> — once resolved, close with e-signature to keep the queue clean</li></ul><p><strong>Ready for the quiz!</strong></p>')
) AS s(idx, title, content)
WHERE c.course_code = 'QUERY-MGMT'
AND NOT EXISTS (SELECT 1 FROM acc_training_slides WHERE course_id = c.id);
